### PR TITLE
SOLR-14882

### PR DESCRIPTION
**Pull request by epugh**
Fixing up the .jsonl versus .json format on `bin/solr export`.

### CODE REVIEW

**Comment by arafalov** [comment]
Does it actually export jsonl though? I did not test.

Also, while we are correcting all of these, can we fix the "usage line" that currently seems to fallback to SolrCLI:
> $ bin/solr export -help
> usage: org.apache.solr.util.SolrCLI

By comparison:
> $ bin/solr create_core -help
> Usage: solr create_core [-c core] [-d confdir] [-p port] [-V]

**Comment by epugh** [comment]
It does export `jsonl` instead of `json`!   Good thought on the help...

**Comment by epugh** [comment]
Can you check on master @arafalov as I just ran it and got help docs:

```
➜  solr-9.0.0-SNAPSHOT git:(SOLR-14882) bin/solr export -help                                                                       
usage: org.apache.solr.util.SolrCLI
 -fields <arg>   Comma separated fields. By default all fields are fetched
 -format <arg>   format  jsonl/javabin, defaults to jsonl. file extension
                 will be .jsonl
 -help           Print this message
 -limit <arg>    Max number of docs to download. default = 100, use -1 for
                 all docs
 -out <arg>      file name . defaults to collection-name.<format>
 -query <arg>    A custom query, default is *:*
 -url <arg>      Address of the collection, example
                 http://localhost:8983/solr/gettingstarted
 -verbose        Generate verbose log messages
```

**Comment by arafalov** [comment]
> Can you check on master @arafalov as I just ran it and got help docs:
> 
> ➜  solr-9.0.0-SNAPSHOT git:(SOLR-14882) bin/solr export -help                                                                       
> usage: org.apache.solr.util.SolrCLI

^^^^^^^^^^^^^^^^^^^

Yes, it is just that first line I was commenting on. It should talk about the command, not about the java tool that executes it.

**Comment by madrob** [comment]
Please add a CHANGES entry

**Comment by epugh** [comment]
Okay, so @arafalov  I am having NO luck in finding the text `usage:` or where it is comiong from...   I can live with it...

**Comment by epugh** [comment]
Okay, working on testing the CURL commands in the solr-control-script-reference.adoc...    I am not able to do this:

```
curl -X POST -d @big.jsonl http://localhost:8983/solr/dude2/update/json/docs?commit=true
```

So, did I miss soemthing, maybe we aren't doing JSONL...

**Comment by arafalov** [comment]
> Okay, so @arafalov I am having NO luck in finding the text `usage:` or where it is comiong from... I can live with it...

It helps to see where other invocations do it. So, it seems to be something about:
```
      if (cli.getOptions().length == 0 || cli.getArgs().length > 0 || cli.hasOption("h")) {
        new HelpFormatter().printHelp("bin/solr utils [OPTIONS]", getToolOptions(this));
        return 1;
      }
```

This tool does not have it, so probably falls back to default implementation that constructs default message with getOptions() instead. Not the end of the world, but would have been nice to fix.

**Comment by epugh** [comment]
Okay, turns out my not loading json was due to something odd in the sample data I exported (sigh)...  However, the more_books.jsonl works just fine.

**Comment by epugh** [comment]
This is why we need a full overhaul of the SolrCLI, get all this logic out of the solr shell and cmd files, and into Java, and have one way of doing everything!

**Comment by noblepaul** [comment]
can you please add a title?

**Comment by epugh** [comment]
I'm going to take the good parts of this PR and add them to SOLR-15152 in #2356

**Pull request closed without merging**
