### PR TITLE
[SOLR-13663] Span Positional Range Support in XML Query Parser + test

### PR DESCRIPTION
**Pull request by alessandrobenedetti**
# Description

Currently the XML Query Parser support a vast array of span queries, including the SpanFirstQuery, but it doesn't support the generic SpanPositionRangeQuery.
< SpanPositionRange start="2" end="3">
<SpanTerm fieldName="title">prejudice</SpanTerm>
</ SpanPositionRange>
 

# Solution

Scope of this issue is to introduce the related java builder and allow the possibility to build such queries.

# Tests

org.apache.lucene.queryparser.xml.TestCoreParser#testSpanPositionRangeQueryXML

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [ ] I am authorized to contribute this code to the ASF and have removed any code I do not have a license to distribute.
- [x] I have developed this patch against the `master` branch.
- [x] I have run `ant precommit` and the appropriate test suite.
- [x] I have added tests for my changes.
- [x] I have added documentation for the Ref Guide (for Solr changes only).

### CODE REVIEW

**Comment by alessandrobenedetti** [comment]
https://lucene.apache.org/solr/guide/8_1/other-parsers.html#xml-query-parser

For the documentation it will be necessary to edit this page and add the new SpanQuery in the list with the reference to the java Builder.
It will be a minimal change.

**Comment by cpoerschke** [comment]
Hello @alessandrobenedetti 

> ... For the documentation it will be necessary to edit ...

In case you wanted to edit the documentation alongside the code changes here, just to let you know that the documentation source now lives in the same repo i.e. https://github.com/apache/lucene-solr/blob/master/solr/solr-ref-guide/src/other-parsers.adoc in this case. Hope that helps.

**Comment by alessandrobenedetti** [comment]
Thanks @cpoerschke for the suggestion, it has been very helpful.
I just edited the doc and contributed it back.
I guess the javadoc will be automatically generated, so the small change contributed should be fine.

**Comment by mkhludnev** [comment]
@alessandrobenedetti would you mind to close this PR.

**Comment by alessandrobenedetti** [comment]
Done!

**Pull request closed without merging**
