### PR TITLE
LUCENE-9647 Add back github action for Ant

### PR DESCRIPTION
**Pull request by madrob**
https://issues.apache.org/jira/browse/LUCENE-9647

Tagging @tflobbe for review because you removed the file in the first place. If there's a better place to put it, let me know.

### CODE REVIEW

**Comment by tflobbe** [comment]
Does this go yo master or to 8.x branch? I don't think we had it running in 8.x before?

**Comment by madrob** [comment]
It needs to be in the default branch. That we didn't have this for 8.x before isn't a reason not to add it now.

**Review by anshumg — APPROVED** [review]

**Comment by tflobbe** [comment]
> That we didn't have this for 8.x before isn't a reason not to add it now.
+1! didn't mean we shouldn't, I was just referring to the fact that I didn't remove it for a particular reason, it just never existed for this branch.

**Comment by dweiss** [comment]
Why merge it with master though? It does not apply to master - only to 8x?

**Comment by dweiss** [comment]
bq. It needs to be in the default branch. 

Oh, ok. So it needs to be on the default branch even if it applies only to a filtered set of branches? Get it.

**Pull request merged**
