### PR TITLE
SOLR-8138: Simple UI for issuing SQL queries

### PR DESCRIPTION
**Pull request by epugh**
This code was mostly written by Michael Suzuki in PR https://github.com/apache/lucene-solr/pull/180,  i just tweaked it to load in Solr 9, and updated the version of ui-grid to the 4.10 version.

# Description

Add a simple page to Solr Admin for doing SQL queries.

# Solution

Delegates to the `qt=sql` handler and runs the query.  Displays results in basic table.

This UI shows how easy it is to write a SQL query that Solr doesn't like ;-(.   However, it's much easier to use than using Curl.   And may encourage more use of this powerful feature.

# Tests

Please describe the tests you've developed or run to confirm this patch implements the feature or solves the problem.

# Checklist

Please review the following and check all that apply:

- [X ] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [ X] I have created a Jira issue and added the issue ID to my pull request title.
- [ X] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [X ] I have developed this patch against the `master` branch.
- [ X] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [X ] I have added documentation for the [Ref Guide](https://github.com/apache/lucene-solr/tree/master/solr/solr-ref-guide) (for Solr changes only).

### CODE REVIEW

**Comment by epugh** [comment]
@michaelsuzukisagi I'd love your review.

**Comment by epugh** [comment]
I think I'm done with this PR!   I'd love a review and then I'll commit it.   I could see backporting it to 8.x as well.

**Review by janhoy — COMMENTED** [review]
LGTM. Do we need to add a short credit to ui-grid in LICENSE.txt? I'm confused about when to use NOTICE and LICENSE, but I think it should go in one of them?

**Comment by epugh** [comment]
are you referring to the `/solr/licenses/` directory?   A `/solr/licenses/ui-grid-LICENSE.txt` and `/solr/licenses/ui-grid-NOTICE.txt`?

Be nice to add this to the dev docs!

**Comment by epugh** [comment]
also, I don't see any licenses for the JS libraries....

**Comment by epugh** [comment]
How do we get a clarificaiton on this?

**Comment by janhoy** [comment]
So I think you add a few lines at bottom of `solr/LICENSE.txt`, you already see the jquery part there.
I have been adding some sections to `solr/NOTICE.txt` earlier, but I think some of those really belong in LICENSE.txt instead, since only some projects and licenses require use of NOTICE. So a cleanup is needed too...

**Comment by epugh** [comment]
ahh!  I didn't know abouit that!

**Pull request merged**
