### PR TITLE
LUCENE-9007: MockSynonymFilter should add TypeAttribute

### PR DESCRIPTION
**Pull request by cbuescher**
The MockSynonymFilter should add the type TypeAttribute to the synonyms it
generates in order to make it a better stand-in for the real filter in tests.

### CODE REVIEW

**Comment by uschindler** [comment]
Looks fine. No other test changes needed?

**Comment by cbuescher** [comment]
@uschindler Don't think so, I ran `ant test` for the lucene directory, didn't find any references to this test filter in the solr part. Other existing test using this filter don't seem to bother about the additional attribute. Don't know what to make about the error in the precommit check here though, any way to re-run this?

**Comment by uschindler** [comment]
No idea about the precommit check. I can look into that tomorrow. Should I take the issue. Looks fine to me and it allows is to create better tests in the future.

**Comment by cbuescher** [comment]
> No idea about the precommit check. I can look into that tomorrow.

I ran precommit locally again and didn't get the failure that I see here in the PR. Just wanted to know if there are ways to re-run it from here or if it was a requirement that it passes.

> Should I take the issue?

Would be nice. I don't know which branches other than master are active atm but would also be nice to get this in some of the near-future release branches. At the moment I'm duplicating the mock filter to get the enhanced behaviour.

**Comment by cbuescher** [comment]
Hi @uschindler, thanks again for the feedback, just wondering if you are interested in taking another look and merge the PR or if there is anything I can add or should change?

**Comment by cbuescher** [comment]
@uschindler quick ping again, is there anything this PR needs or would you approve and merge it? No urgency, just going through my list of open issues.

**Comment by cbuescher** [comment]
Moved to https://github.com/apache/lucene/pull/23 after the lucene/solr split.

**Pull request closed without merging**
