### PR TITLE
SOLR-13391: Add variance and standard deviation stream evaluators

### PR DESCRIPTION
**Pull request by NazerkeBS**
@joel-bernstein, please have a look to the code.

### CODE REVIEW

**Comment by risdenk** [comment]
Out of curiusity, can you wrap the new `var` evaluator with the `sqrt` evaluator to get stddev? Not sure we can use them together to make the new stddev evaluator.

**Comment by joel-bernstein** [comment]
> Out of curiosity, can you wrap the new `var` evaluator with the `sqrt` evaluator to get `stddev`? Not sure we can use them together to make the new `stddev` evaluator.

The Java implementations don't have a great way doing that. You could do that easily with the expression language though. The java implementation assume that they are being passed information through the expression parser.

**Comment by joel-bernstein** [comment]
The implementations look great. There are couple places to add tests.
The MathExpressionTest.java has all the math expression tests. You can use testDotProduct as an example.

And TestLang.java just needs the new functions to be added to the allFunctions array.

To run the tests:

ant test -Dtestcase=MathExpressionTest
ant test -Dtestcase=MathExpressionTest -Dtests.method=testDotProduct

Thanks for the contribution!

**Comment by NazerkeBS** [comment]
I added a separate test for the variance and the standard deviation. It works now.

**Comment by joel-bernstein** [comment]
Here is how it looks from Zeppelin-Solr interpreter
Screen Shot 2018-08-17 at 9 08 45 AM

**Comment by joel-bernstein** [comment]
Screen Shot 2019-04-12 at 9 11 48 AM

**Comment by joel-bernstein** [comment]
This is pretty much ready to go. Thanks again for the contribution.

I should be able to get this in for the next release. It will be listed in the CHANGES.txt as:

SOLR-13391: Add variance and standard deviation stream evaluators (Nazerke Seidan, Joel Bernstein)

Let me know if you'd like your name listed differently.

**Comment by NazerkeBS** [comment]
I think, that is fine. In the future I would like to contribute more for streaming expressions as I am working on this topic.

**Comment by joel-bernstein** [comment]
> I think, that is fine. In the future I would like to contribute more for streaming expressions as I am working on this topic.

Ok, ping me if you have a PR to look at. Also let me know if you want suggestions for things to work on.

**Comment by NazerkeBS** [comment]
I would be so grateful if you could give me a few suggestions to work on.

**Comment by joel-bernstein** [comment]
Ok, this is a great ticket to work on:
https://issues.apache.org/jira/browse/SOLR-13047
I'll update it with some thoughts on how to get started.

**Comment by janhoy** [comment]
@joel-bernstein you could close this PR, not?

**Comment by joel-bernstein** [comment]
This can be closed, but I don't have permission to close it apparently. I also currently are not setup to merge PR's.

**Comment by ctargett** [comment]
@joel-bernstein Have you linked your GH and ASF accounts? It's a simple procedure of adding your GH ID to your ASF profile: https://reference.apache.org/committer/github. Once its sync'd you should be able to fully edit/merge PRs.

**Comment by ctargett** [comment]
Closed PR since the code has been merged and released.

**Pull request closed without merging**
