### PR TITLE
SOLR-14603: update Restlet version 

### PR DESCRIPTION
**Pull request by MarcusSorealheis**
# Description

CVEs in current version

# Solution

Upgrade the version to `2.4.3`

# Tests

Please describe the tests you've developed or run to confirm this patch implements the feature or solves the problem.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `master` branch.
- [x] I have run `ant precommit` and the appropriate test suite.
- [ ] I have added tests for my changes.
- [x] I have added documentation for the [Ref Guide](https://github.com/apache/lucene-solr/tree/master/solr/solr-ref-guide) (for Solr changes only).

### CODE REVIEW

**Comment by janhoy** [comment]
Need to update gradle build and sha files too :)

**Comment by MarcusSorealheis** [comment]
> Need to update gradle build and sha files too :)
I just read that I need to update checksums. On it.

**Comment by MarcusSorealheis** [comment]
I think this finally ready. For some reason, my checksums locally were not working well.

**Comment by MarcusSorealheis** [comment]
Everything is fine. I don't where I got those first checksums from. I don't recall specifying a different algorithm. :)

**Comment by chatman** [comment]
+1, LGTM.

**Comment by chatman** [comment]
This is merged. Please close the PR. Thanks!

**Comment by risdenk** [comment]
Closing since sasys this was merged - also restlet was removed down the line anyway - https://issues.apache.org/jira/browse/SOLR-14659

**Pull request closed without merging**
