### PR TITLE
SOLR-13655:Upgrade Collections.unModifiableSet to Set.of and Set.copyOf

### PR DESCRIPTION
**Pull request by atris**

### CODE REVIEW

**Comment by atris** [comment]
Any thoughts on this? Seems safe enough to merge?

**Comment by atris** [comment]
Gentle Ping

**Comment by tflobbe** [comment]
Thanks @atris. Changes look good to me, however, I think there are a couple more cases that we could change:
* `ConfigNameConstants`
* `Variable.Type`
* `SolrRequest`
* `ZkStateReader.KNOWN_CLUSTER_PROPS`

**Comment by atris** [comment]
@tflobbe Thanks, for some reason, my grep command missed those ones. Updated the PR with the same.

**Comment by atris** [comment]
@tflobbe Thanks. I was slightly unsure about whether these sections actually need an immutable copy of the original set (by their usage patterns), hence was being conservative by doing copyOf instead of of(). However, post your comment, I looked at the call sites of these methods and they look to be fine with an immutable reference, so changed the calls.

**Comment by tflobbe** [comment]
Thanks @atris! squashed/merged

**Comment by atris** [comment]
Thanks @tflobbe !

**Pull request merged**
