### PR TITLE
LUCENE-8753: UniformSplitPostingsFormat

### PR DESCRIPTION
**Pull request by bruno-roustant**
Follow up of PR https://github.com/apache/lucene-solr/pull/633

Moves DeltaBaseTermStateSerializer inside uniformsplit package.
Adds lucene.experimental annotation to all classes.
Adds package javadoc.

### CODE REVIEW

**Comment by dsmiley** [comment]
@bruno-roustant I think there's a bugfix missing here regarding the lack of BlockDecoder/Encoder on the term dictionary (e.g. for encryption).

**Comment by bruno-roustant** [comment]
I added a new commit to integrate SharedTerms (same as PR#676 now obsolete).
It also fixes the lack of BlockEncoder for the FST.

**Comment by dsmiley** [comment]
Thanks; looks good Bruno.

**Comment by dsmiley** [comment]
Merged: https://github.com/apache/lucene-solr/commit/b963b7c3dbecda86c2917ad341caee63b93815ac

**Pull request closed without merging**
