### PR TITLE
LUCENE-9605: update snowball to d8cf01ddf37a, adds Yiddish

### PR DESCRIPTION
**Pull request by rmuir**
Just merged their master branch, regenerated the patch file, and reran `gradlew snowball`, precommit and tests.

### CODE REVIEW

**Comment by dweiss** [comment]
LGTM. Just scratching my head about one thing - the generator has that extra field now yet the patch doesn't contain diffs for other languages - only Serbian and Yiddish?

**Comment by uschindler** [comment]
+1

**Comment by rmuir** [comment]
> Just scratching my head about one thing - the generator has that extra field now yet the patch doesn't contain diffs for other languages - only Serbian and Yiddish?

@dweiss Which extra field?

**Comment by dweiss** [comment]
This one?

https://github.com/apache/lucene-solr/pull/2077/files#diff-455f29a3b76e17c21dded0a5f1b853145bfa7e6e5f1f36c52012a5f124e14ac2R589

**Comment by rmuir** [comment]
There isn't any changes here. It's confusing because its showing a diff of a patch file, and github is highlighting something in green that isn't a change. The only thing that actually changed in the patch file are the line numbers of patch chunks.

**Comment by dweiss** [comment]
Duh. I see it now... darn, sorry for the noise.

**Comment by rmuir** [comment]
It's not your fault, this is why its good to try to work down this patch file, it is confusing.

**Pull request merged**
