### PR TITLE
SOLR-14132: Upgrade Angular JS 1.3.8 to 1.7.9

### PR DESCRIPTION
**Pull request by risdenk**
* Upgrade Angular JS 1.3.8 to 1.7.9
* Upgrade Angular Chosen v1.3.0 and Chosen to v1.8.7
* Remove older jquery 1.7.2 version
* Remove non minified Angular JS files

Signed-off-by: Kevin Risden <krisden@apache.org>

### CODE REVIEW

**Comment by janhoy** [comment]
Even links to collection-overview http://localhost:8983/solr/#/foo/collection-overview will break. I found 8 occurences of the string `solr/#/` in the ref-guide.

**Comment by risdenk** [comment]
Yea I saw the potential to change the hashPrefix. I'll take a look and see how it works.

**Comment by risdenk** [comment]
Thanks @janhoy for the initial review. I tried updating the hash prefix and that looks to work. I pushed a new update with that change reverting all the link changes.

**Comment by janhoy** [comment]
Great. I have not re-tested but trust that your tests prove that it works.

**Pull request closed without merging**
