### PR TITLE
SOLR-15009 Propogate IOException from DF.exists

### PR DESCRIPTION
**Pull request by madrob**
https://issues.apache.org/jira/browse/SOLR-15009

### CODE REVIEW

**Comment by madrob** [comment]
@dsmiley  you might find this interesting based on your other comment about Path v File

**Review by dsmiley — APPROVED** [review]
LGTM

**Comment by madrob** [comment]
@TomMD musebot seems to be stuck - any ideas?

**Comment by TomMD** [comment]
@madrob I see a backend failure which lacks sufficient explanation.  We have opened a ticket to investigate further.  In the mean time I have re-started analysis of this PR.  I can babysit this - if the job does not finish within the next hour then we'll have more to investigate.  Thank you for asking about this, it's certainly not a situation that should come up.

**Comment by madrob** [comment]
Committed in cb5ba42bd7d9777eaf76705f17a3407fd2897b10

**Pull request closed without merging**
