### PR TITLE
LUCENE-9385: (Backporting) Add FacetsConfig option to control which drill-down terms are indexed for a FacetLabel

### PR DESCRIPTION
**Pull request by zacharymorn**
This PR backports changes from https://github.com/apache/lucene/pull/25 into Lucene 8x

I have run `ant clean; ant precommit; ant test` to validate the changes.

### CODE REVIEW

**Comment by mikemccand** [comment]
Aha, thank you @zacharymorn!  I'll have a look.

Out of curiosity: were you able to use git somehow to cherry-pick across the repositories/branches?  Or did you diff/patch?

**Comment by mikemccand** [comment]
Also, were there any conflicts you had to resolve manually?  Or it was smooth sailing?

**Comment by mikemccand** [comment]
Thanks @zacharymorn!

**Review by mikemccand — APPROVED** [review]

**Comment by zacharymorn** [comment]
HI @mikemccand , thanks for approving and merging the changes! I researched around cross-repo cherry-picking and found that git seems to support it to some extend, but may still require manual conflict resolution effort. The steps / commands I ran inside the old lucene-solr repo on branch `branch_8x` are:
1. `git remote add lucene https://github.com/apache/lucene.git`
1. `git fetch lucene`
1. `git branch lucene_main lucene/main`
1. `git log lucene_main` # to get the commit hash
1. `git checkout -b branch_8x_backporting_LUCENE-9385_skip_drilldown`
1. `git cherry-pick -x 3648a1020a8ab`

At this point git showed me there was conflict for `FacetsConfig.java`, in basically all sections of code I had changed, so I had to resolve them manually. However, I noticed it did not report any conflict for new tests in the test classes, so I guess it can handle cross-repo addition fine, but may report on conflict for modification.

**Pull request merged**
