### PR TITLE
SOLR-13203: Added 400 status code to exception in DynamicField

### PR DESCRIPTION
**Pull request by mrsoong**
# Description

The RuntimeException that the DynamicField parser throws is never caught. In at least one case this results in a 500 error being thrown.

# Solution

Replaced the RuntimeException with a SOLRException with an error code set to 400

# Tests

Added TestExtendedDismaxParser.testInvalidDynamicField which covers DynamicField for an invalid input that can cause this bug

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title. (Existing issue)
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `master` branch.
- [x] I have run `ant precommit` and the appropriate test suite.
- [x] I have added tests for my changes.
- [ ] I have added documentation for the [Ref Guide](https://github.com/apache/lucene-solr/tree/master/solr/solr-ref-guide) (for Solr changes only).

### CODE REVIEW

**Comment by madrob** [comment]
LGTM needs a changed entry, will try to commit this week if nobody else has eyes on

**Comment by mrsoong** [comment]
I forgot to link the appropriate JIRA issue, sorry about that. The title should be correct now.

**Comment by mrsoong** [comment]
Hi @madrob. Just wanted to drop a friendly reminder that this PR is still waiting for the changed entry that you mentioned more than a week ago.

**Comment by munendrasn** [comment]
@mrsoong Thanks for the contribution. I have included your GitHub username in the changes.txt. Let me know if that needs to be modified

**Comment by mrsoong** [comment]
Thank you for helping to get this merged @munendrasn. The new entry in changes.txt looks good.

**Pull request merged**
