### PR TITLE
SOLR-15191: Fix faceting on EnumFieldType

### PR DESCRIPTION
**Pull request by thomaswoeckinger**
# Description

Please provide a short description of the changes you're making with this pull request.

# Solution

Please provide a short description of the approach taken to implement your solution.

# Tests

Please describe the tests you've developed or run to confirm this patch implements the feature or solves the problem.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [ ] I have developed this patch against the `master` branch.
- [ ] I have run `./gradlew check`.
- [x] I have added tests for my changes.
- [ ] I have added documentation for the [Ref Guide](https://github.com/apache/lucene-solr/tree/master/solr/solr-ref-guide) (for Solr changes only).

### CODE REVIEW

**Comment by dsmiley** [comment]
Instead of the instanceof checks (kinda brittle code-smell, not flexible), maybe we can call `FieldType.getNumberType() != null` ?

Can you please run all tests, e.g. `/gradlew check`

**Comment by thomaswoeckinger** [comment]
> Instead of the instanceof checks (kinda brittle code-smell, not flexible), maybe we can call `FieldType.getNumberType() != null` ?
>
That is already done in FacetFieldProcessorByHashDV.calcFacets which is the only position which is using this method, and i agree with you it's kind of a code smell.

There are two alternatives (i don't really like one of them):

a.) Move the getNumberType()!=null check into the method but than i have to catch the exception outside or breaking the behavior.

b.) Copy only the switch case statement to FacetFieldProcessorByHashDV.calcFacets.
 
> Can you please run all tests, e.g. `/gradlew check`
I already run ant test, there are no test failures.

**Comment by dsmiley** [comment]
Maybe I'm missing something but my suggestion is (in my head) very simple.  Remove the line `if (ft instanceof TrieField || ft.isPointField())` and closing brace for it, and perhaps also the "else" side.  The `default` case of the switch I think should handle the null.  If this won't work then why not?

**Comment by thomaswoeckinger** [comment]
> Maybe I'm missing something but my suggestion is (in my head) very simple. Remove the line `if (ft instanceof TrieField || ft.isPointField())` and closing brace for it, and perhaps also the "else" side. The `default` case of the switch I think should handle the null. If this won't work then why not?

I fully understand your suggestion, the first PR was done with minimal changes only to avoid side effects. 
I pushed again and refactored the method a bit more, just a note switch can not handle null in java, anyway have look.

**Comment by dsmiley** [comment]
Thanks; looks good to me and is simpler too.  I ran tests.  Can you propose a CHANGES.txt entry please?  I suppose one aspect of this is a bug as indicated in your JIRA text (so it goes there), but maybe also list this under improvements (or optimizations?) saying something like: the hash method of json faceting now supports enum field types and perhaps some custom ones too.

I normally go from master and cherry pick to 8x but I suppose there is no harm in going the other way here.

**Comment by thomaswoeckinger** [comment]
> Thanks; looks good to me and is simpler too. I ran tests. Can you propose a CHANGES.txt entry please? I suppose one aspect of this is a bug as indicated in your JIRA text (so it goes there), but maybe also list this under improvements (or optimizations?) saying something like: the hash method of json faceting now supports enum field types and perhaps some custom ones too.
> 

Is 'David Smiley, Thomas Wöckinger' sufficent as authors at the end of the line?

> I normally go from master and cherry pick to 8x but I suppose there is no harm in going the other way here.

I know, this is due to the fact i have not started development against 9.x at the moment, this is on the road map next month

**Pull request merged**
