### PR TITLE
SOLR-13592: Introduce EmbeddedSolrTestBase for better integration tests

### PR DESCRIPTION
**Pull request by thomaswoeckinger**
To allow better integration of EmbeddedSolrServer, hidden implementation should be moved out of SolrJettyTestBase

### CODE REVIEW

**Comment by thomaswoeckinger** [comment]
@gerlowskija plz review

**Comment by thomaswoeckinger** [comment]
@gerlowskija Any progress on this PR?

**Comment by thomaswoeckinger** [comment]
@gerlowskija Anything new?

**Comment by thomaswoeckinger** [comment]
Need any support, or are you just busy at the moment?

**Comment by thomaswoeckinger** [comment]
Still nothing?

**Comment by thomaswoeckinger** [comment]
@gerlowskija Are you still working on this?

**Comment by thomaswoeckinger** [comment]
Rebased again, @gerlowskija it is two weeks ago since last notice, maybe someone else could takeover the review if jason is to busy?

**Comment by thomaswoeckinger** [comment]
@gerlowskija i saw you are working on other issues too, so i hope you have time to get this PR done, if not so maybe you can hand over to another reviewer.

**Comment by gerlowskija** [comment]
My apologies Thomas, my gmail filters weren't letting through github notifications and I didn't see this until you pinged me in JIRA.

This all looks good to me, except for the whitespace formatting, which we've talked about on other PRs.  Github makes it easy to hide introduction/removal of trailing whitespace, but other changes are harder to hide and make the diff noisier to read and harder to review with confidence: adding "final" modifiers to existing variables, breaking up long method signatures onto multiple lines, etc.  Would you mind scrubbing some of those changes from this PR?

In the meantime, I'm going to start "beasting" (run {{ant test-help}} for info) this PR to make sure that none of the affected tests have any flaky failures.  I'll comment again in a day or two with some results.  (If you want to help out, you can also run some beast-runs if your machine allows it.)

Thanks for your continued patience.

**Comment by thomaswoeckinger** [comment]
> My apologies Thomas, my gmail filters weren't letting through github notifications and I didn't see this until you pinged me in JIRA.
> 

:-), no problem, i am still interest to get this in!
Do you know if there are any plans on the master branch migrating to junit 5, this would allow to write tests using default interfaces, so it would be very easy to let them run under different scenarios like embedded, jetty, cloud and so on.

> This all looks good to me, except for the whitespace formatting, which we've talked about on other PRs. Github makes it easy to hide introduction/removal of trailing whitespace, but other changes are harder to hide and make the diff noisier to read and harder to review with confidence: adding "final" modifiers to existing variables, breaking up long method signatures onto multiple lines, etc. Would you mind scrubbing some of those changes from this PR?

Yes we talked about, my point: why using common format rules if even no one is using them.
But anyway, i can take a look at the method signatures, if you like, but i think it is not that difficult to review at the current state.
 
> 
> In the meantime, I'm going to start "beasting" (run {{ant test-help}} for info) this PR to make sure that none of the affected tests have any flaky failures. I'll comment again in a day or two with some results. (If you want to help out, you can also run some beast-runs if your machine allows it.)
> 
> Thanks for your continued patience.

i will have a look at it, the default test are all running on my site, i will comment on this PR when i have results.

And you are very welcome with your comments and suggestions!

**Comment by thomaswoeckinger** [comment]
Did not had time to test yet, i am at vacation for the next to week, than i can continue to work on it.

**Comment by gerlowskija** [comment]
I haven't heard anyone bring up JUnit 5, no.  We'll have to do it eventually, but it could potentially be a massive change for Solr, so my guess is that no one will push for it until they absolutely have to.

**Comment by gerlowskija** [comment]
Is there any difference between LargeVolumeEmbeddedTest, LargeVolumeJettyTest, and LargeVolumeBinaryJettyTest?  It looks like all three are exactly the same with this PR.  They look suspiciously similar before this PR too, so I think the problem pre-exists this change.  But it's still very odd.  Just wondering if you dug into that at all as you were working?

**Comment by thomaswoeckinger** [comment]
> Is there any difference between LargeVolumeEmbeddedTest, LargeVolumeJettyTest, and LargeVolumeBinaryJettyTest? It looks like all three are exactly the same with this PR. They look suspiciously similar before this PR too, so I think the problem pre-exists this change. But it's still very odd. Just wondering if you dug into that at all as you were working?

They are using old init from my point of view, all other Jetty tests are using initCore().

**Comment by thomaswoeckinger** [comment]
Any plans on merging this back to 8.x?

**Comment by thomaswoeckinger** [comment]
I will close the coresponding issue now.

**Comment by dsmiley** [comment]
Note that the javadocs on `org.apache.solr.SolrJettyTestBase#createNewSolrClient` is obsolete as it still references using an "embedded implementation" which is no longer true.

**Comment by thomaswoeckinger** [comment]
> Note that the javadocs on `org.apache.solr.SolrJettyTestBase#createNewSolrClient` is obsolete as it still references using an "embedded implementation" which is no longer true.

I will remove the reference in the followup PR #665 .

**Pull request closed without merging**
