### PR TITLE
SOLR-13762: Add binary support to XMLCodec

### PR DESCRIPTION
**Pull request by thomaswoeckinger**
# Description

Please provide a short description of the changes you're making with this pull request.

# Solution

Please provide a short description of the approach taken to implement your solution.

# Tests

Please describe the tests you've developed or run to confirm this patch implements the feature or solves the problem.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I am authorized to contribute this code to the ASF and have removed any code I do not have a license to distribute.
- [x] I have developed this patch against the `master` branch.
- [x] I have run `ant precommit` and the appropriate test suite.
- [x] I have added tests for my changes.
- [ ] I have added documentation for the [Ref Guide](https://github.com/apache/lucene-solr/tree/master/solr/solr-ref-guide) (for Solr changes only).

### CODE REVIEW

**Comment by thomaswoeckinger** [comment]
@gerlowskija please review

**Comment by thomaswoeckinger** [comment]
@gerlowskija Ready to merge?

**Comment by thomaswoeckinger** [comment]
@gerlowskija Anything new on this one?

**Comment by thomaswoeckinger** [comment]
@gerlowskija plz review.

**Comment by gerlowskija** [comment]
Thanks @thomaswoeckinger , and sorry for the delay.  This updated code lgtm and I'll merge today after running the tests.

**Pull request closed without merging**
