### PR TITLE
LUCENE-8984: MoreLikeThis MLT is biased for uncommon fields

### PR DESCRIPTION
**Pull request by andyhind**
# Description

Fix MLT not to be biased for fields with few docs

# Solution

Use the per field doc count

# Tests
 
Tests with uncommon and common fields

# Checklist

Please review the following and check all that apply:

- [x ] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x ] I have created a Jira issue and added the issue ID to my pull request title.
- [ x] I am authorized to contribute this code to the ASF and have removed any code I do not have a license to distribute.
- [ x] I have developed this patch against the `master` branch.
- [x ] I have run `ant precommit` and the appropriate test suite.
- [x ] I have added tests for my changes.
- [ Not required] I have added documentation for the [Ref Guide](https://github.com/apache/lucene-solr/tree/master/solr/solr-ref-guide) (for Solr changes only).

### CODE REVIEW

**Comment by anshumg** [comment]
@andyhind This LGTM, but can we move this to be a LUCENE JIRA instead? Once that's done, I'll be happy to merge this in. Also, if you could add a CHANGELOG entry, it'd be great.

**Comment by andyhind** [comment]
Hi

Are you expecting a Jira move? If so, I do not have the rights to do this. I will sort the change log.

Andy

**Comment by anshumg** [comment]
Sorry, didn't realize you couldn't move the JIRA. I did that.
I can add the changelog entry later today and merge this in as well if you don't get to it. If you do, please remember to add this to both, Lucene and Solr change log as it affects both.

**Comment by andyhind** [comment]
I have updated both CHANGES.txt

**Comment by anshumg** [comment]
Thank you @andyhind

**Pull request merged**
