### PR TITLE
Backport SOLR-14765 to branch_8_11

### PR DESCRIPTION
**Pull request by risdenk**
https://issues.apache.org/jira/browse/SOLR-14765

backports SOLR-14765 and follow up bug fix/test commits.

### CODE REVIEW

**Comment by itygh** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by HoustonPutman** [comment]
Given that I have yet to have a passing build, hopefully this helps!

**Comment by HoustonPutman** [comment]
Hey @risdenk are you still planning on getting this in?

**Comment by risdenk** [comment]
Sorry for delayed response @HoustonPutman no need to wait for me

**Comment by itygh** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Pull request closed without merging**
