### PR TITLE
LUCENE-9169: Add Github Workflow for Gradle Wrapper Validation

### PR DESCRIPTION
**Pull request by eskatos**
# Description

This workflow validates the checksums of Gradle Wrapper JAR files present in the source tree and fails if unknown Gradle Wrapper JAR files are found.

# Solution

See https://github.com/marketplace/actions/gradle-wrapper-validation

# Tests

N/A

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `master` branch.

### CODE REVIEW

**Comment by janhoy** [comment]
This workflow was triggered on a push to my fork (https://github.com/cominvent/lucene-solr/commit/9bae9c71ef632e141adedadc7ccfccabe2ca353d/checks?check_suite_id=419459737) and I got an error email. Can you disable for forks?

**Comment by dweiss** [comment]
Ouch. I thought it is a free service? If it is a paid option then I will
revert.

D.

**Comment by eskatos** [comment]
It's a free service. But Github organizations with legacy Github paid plans can't run Github Actions yet. I suppose `cominvent` has a legacy paid plan.

**Comment by eskatos** [comment]
@janhoy, you can disable Github Actions on your fork, go to `Settings > Actions` and select `Disable Actions for this repository`

**Comment by eskatos** [comment]
Also note that this isn't limited to this workflow. The existing `.github/workflows/ant.yml` caused the same issue on your fork 4 days ago. See https://github.com/cominvent/lucene-solr/actions

**Pull request merged**
