### PR TITLE
SOLR-14297: replace commons-codec Base64 with JDK8 Base64

### PR DESCRIPTION
**Pull request by asalamon74**
# Description

Java8 has a builtin Base64 encoder and decoder, there is no need to use commons-codec for this purpose.

# Solution

Eliminate commons-codec Base64 usage

# Tests

Unit tests

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `master` branch.
- [x] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Ref Guide](https://github.com/apache/lucene-solr/tree/master/solr/solr-ref-guide) (for Solr changes only).

### CODE REVIEW

**Comment by HoustonPutman** [comment]
Since Base64.Encoder and Base64.Decoder are thread-safe, it might be better to have static implementations of each for each class here, instead of generating one per request.

Otherwise this looks pretty straightforward!

**Comment by asalamon74** [comment]
It seems to me `getDecoder()` and `getEncoder()` does not generate a new decoder/encoder just returns the same one: http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/util/Base64.java#l151

**Review by HoustonPutman — APPROVED** [review]
This looks good to me. The default Base64 method for Java is `Basic` and the default method for Apache Commons is `MIME`. But for the purposes of Basic Auth, I don't believe there should be a difference.

**Comment by HoustonPutman** [comment]
Could you please add an entry to `solr/CHANGES.txt` in the 9.0 section under "Other"?

**Pull request merged**
