### PR TITLE
Fix format indent from 4 to 2 spaces

### PR DESCRIPTION
**Pull request by mayya-sharipova**
Files in org.apache.lucene.search.comparators package
has a wrong indent of 4 spaces instead of 2.
This patch fixes only the indent from 4 to correct 2 spaces

### CODE REVIEW

**Comment by msokolov** [comment]
Thanks for fixing - I have another one I need to do, too, and I wonder if we shouldn't just push uncontroversial changes like this directly? No need to wait for review I think.

**Comment by mayya-sharipova** [comment]
@msokolov  Thanks for your comment. Indeed having a  `gradlew precommit` to fail on inconsistent code style would be useful.

Thanks for feedback, I will merge the PR.

**Comment by ErickErickson** [comment]
It already fails on _tabs_ rather than spaces, but failing on too many spaces isn’t checked.

That said, rather than a one-off for indentation, I’d rather see the effort go here
rather than a separate precommit check….:

https://issues.apache.org/jira/browse/LUCENE-9564 and SOLR-14920…

BTW, 'gradlew check’ does all the precommit tasks as well as run tests...

**Comment by mayya-sharipova** [comment]
@ErickErickson Thanks for your suggestions, and letting me know about LUCENE-9564, I will keep watching this issue.

**Pull request merged**
