### PR TITLE
SOLR-13768 Remove requiresub parameter in JWTAuthPlugin

### PR DESCRIPTION
**Pull request by ravowlga123**
# Description
As per ticket [SOLR-13768](https://jira.apache.org/jira/browse/SOLR-13768) we need to remove support for deprecated 'requireSub' parameter in JWTAuthPlugin

# Solution
Removed the parameter PARAM_REQUIRE_SUBJECT used in JWTAuthPlugin.

# Tests
Ran the full test suite using ant test.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `master` branch.
- [x] I have run `ant precommit` and the appropriate test suite.
- [ ] I have added tests for my changes.
- [x] I have added documentation for the [Ref Guide](https://github.com/apache/lucene-solr/tree/master/solr/solr-ref-guide) (for Solr changes only).

### CODE REVIEW

**Comment by janhoy** [comment]
Thanks for the contribution. I think your implementation is correct, and should be aimed at v9, i.e. master branch only.

Please add a line to CHANGES.txt about the change, as well as a line in reference guide chapter `major-changes-in-solr-9.adoc` so those upgrading can prepare to no longer use the parameter.

**Comment by janhoy** [comment]
Sorry for not following up on this earlier. @ravowlga123 would you mind to bring your branch up to date with master, and then I'll merge it.

**Comment by erikhatcher** [comment]
We need to re-think this change.   I believe we need to use `principalClaim` and bring back, in effect, requiring or not requiring `sub`.

**Comment by ravowlga123** [comment]
@janhoy I have updated the branch but @erikhatcher has concerns regarding the change it seems. Please do let me know your thoughts on above.

**Comment by janhoy** [comment]
Perhaps this can be more dynamic, i.e. we require whatever claim that is configured for `principalClaim` in the config. This defaults to `sub`, but if someone configures e.g. `principalClaim: userid` then we should no longer require the `sub` claim.

So I claim that we don't need an extra config option. Solr needs a principal ID anyway, so we have to require *something*.

**Comment by janhoy** [comment]
Following up on this. Unfortunately we switched to new git repo today, so you'll have to re-open a PR over at https://github.com/apache/solr from this branch.

The easiest is perhaps to fork the new repo, then push your branch ravowlga123:SOLR-13768 to that fork (it has all the history), and open a new PR linking to this one. Or you can export this as a patch (by adding .patch to the URL) and then `git apply`..

**Comment by janhoy** [comment]
@ravowlga123 There is an instruction at https://github.com/apache/lucene-solr/blob/master/PRs.md for how to prepare a PR for the main branch in the new repo. I'll close this, as the 'master' branch of this repository is no longer in use.

**Pull request closed without merging**
