### PR TITLE
Jira/solr 6203

### PR DESCRIPTION
**Pull request by jitka18**
Hello, Christine.  I merged from master though commit 00f0c30 to my fork of the jira/solr-6203 branch, resolved a conflict in TopGroupsFieldCommand.java, and committed.  Unit tests all pass, including those added in previous commits to test the fix of the bug which is the subject of this jira.
I closed the previous pull request because I thought it was interfering with my attempt to create this one.
Judith

### CODE REVIEW

**Comment by cpoerschke** [comment]
Hi Judith - I've just gone to https://github.com/cpoerschke/lucene-solr/settings/collaboration and invited you as a collaborator for my lucene-solr fork here on github. If you'd be happy to do the same then we can send each other pull requests. The two top commits on https://github.com/cpoerschke/lucene-solr/tree/jira/solr-6203 as one PR for example, easier to send a PR rather than comment in the code? Thanks. - Christine

**Comment by jitka18** [comment]
Hi, Christine.  Sounds good---I hope to have time this evening to catch up
with the collaboration business.  Thanks for fixing the indentation in your
most recent commit on your fork.  I suppose the commit before that is a
matter of taste---it seemed strange to me to feed the constructor values
that we know might not be the final ones and then to turn around
immediately and adjust them, but there is less duplication the way you have
it.  Your way is fine with me.  We could probably do some tweaks here and
there and come up with something even cleaner but I'd rather stay focused
for now.
Thanks,
Judith

**Comment by cpoerschke** [comment]
Hi Judith - thanks for adding me to the collaborator list. I've added one more commit to the https://github.com/jitka18/lucene-solr/pull/1 request and would suggest something along the following lines as the next steps:
* to review https://github.com/jitka18/lucene-solr/pull/1 and if it looks good merge it into your jira/solr-6203 branch and/or add comments on the pull request
* to merge the latest master (at the time) into the jira/solr-6203 working branch
** this will give some merge conflicts that need to be resolved
** this will somewhat reduce the scope and complexity of the changes for the working branch since SOLR-10394 part-2 renames will be picked up from the latest master
* to see if new code duplication in DistributedQueryComponentCustomSortTest can be reduced further, this will not just reduce the amount of code but will (i think) also help with clarity i.e. what is being tested

How does that sound? Any questions, please let me know. - Christine

**Comment by jitka18** [comment]
Hi, Christine.  I accepted your pull request and will update my branch from
the  master later today.   Will also take a look at the tests in DQCCST.

Thanks,
Judith

**Comment by cpoerschke** [comment]
Hi Judith,

Thanks for revising the DistributedQueryComponentCustomSortTest extension, I like how your new TestParamsAndOutcome class makes it easier to 'see' the test logic itself.

Also, I just added another small commit to the https://github.com/jitka18/lucene-solr/pull/2 for our working branch, it removes the almost unused get...Sort in favour of the new get...SortSpec - what do you think?

**Pull request closed without merging**
