### PR TITLE
SOLR-15162: Add some parameters to make MODIFYCOLLECTION v1 and v2 more similar.   

### PR DESCRIPTION
**Pull request by epugh**
Not sure on rule, snitch, and policy on if they are still real.

Wish we had docs for rule, snitch, and policy in the Solr Ref Guide page under CREATE, appears to be half fixed.

# Description

Adding some parameters to make V2 match V1.

# Solution

I tested the addition of `readOnly` and it worked great.  I didn't test `rule`, `snitch` or `policy` because I don't understand if they are still real or not, and it was unclear to me from reading the Ref Guide if they existed.   Some cleanup needed there!

# Tests

Manually tested `readOnly` being passed in.

# Checklist

Please review the following and check all that apply:

- [X ] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [ X] I have created a Jira issue and added the issue ID to my pull request title.
- [ X] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [X ] I have developed this patch against the `master` branch.
- [X ] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ X] I have added documentation for the [Ref Guide](https://github.com/apache/lucene-solr/tree/master/solr/solr-ref-guide) (for Solr changes only).

### CODE REVIEW

**Comment by gerlowskija** [comment]
This LGTM, given the large caveat about rule/snitch/policy params.

I bet @sigram would know whether these still exist in 9.0, if he has a chance to chime in here.  But otherwise it might involve some jira digging to understand.

**Comment by epugh** [comment]
Okay, so in digging, appears that the create method is missing the `alias` parameter in V2.

Also, it appears the delete method is missing the `async` parameter in V2.

**Comment by epugh** [comment]
Digging into older Ref Guides and the error messages, I think `rule/snitch/policy` are all gone in 9.

**Comment by epugh** [comment]
I am unclear on the property `collection.configName` or `config` being the right one.  In looking at the `create` command in introspection, it appears to be `config`.

**Pull request merged**
