### PR TITLE
LUCENE-9777: Fix out of date versions on releases 8.7.0 and 8.8.0

### PR DESCRIPTION
**Pull request by iverase**
See https://issues.apache.org/jira/browse/LUCENE-9777.

This seems to bring this part of the release process up-to-date.

### CODE REVIEW

**Comment by iverase** [comment]
Sorry @janhoy, didn't want to take it from you but I got carried over and finally (I think) fix it.

**Comment by eribeiro** [comment]
Two nits worth fixing maybe.

Line 57 declares a test_file variable but never uses it. O guess it was supposed to be used on line 58. 

The last line of the file has a typo in the word 'received'.

**Review by janhoy — APPROVED** [review]
Thanks for discovering and fixing this. I did not assign myself to the JIRA, Noble did, so I'll let you take over :)

**Comment by janhoy** [comment]
DOAP files entry for 8.8.0 is missing from both master and branch_8x. In releaseWizard it is covered in `update_doap` step. @noblepaul or @chatman you may want to handle it in a separate PR.

**Pull request merged**
