### PR TITLE
SOLR-15017: The core's lib/ folder content is not loaded in the classloader anymore when the core's configuration does not define any <lib> element

### PR DESCRIPTION
**Pull request by tmortagne**
Fixes https://issues.apache.org/jira/browse/SOLR-15017

### CODE REVIEW

**Comment by dsmiley** [comment]
+1 LGTM.  I assume you will test this manually?  (good enough). LMK when done; I'll merge this.

**Comment by tmortagne** [comment]
I was wondering where would be the best place to add unit tests actually, I could not find a SolrConfigTest but maybe you have a idea of a place dedicated to SolrConfig validation already.

**Comment by dsmiley** [comment]
See `org.apache.solr.core.TestCoreContainer#testSharedLib` which looks interesting.  You might do something similar and add to TestConfig, and ignore the built-in core in TestConfig since that one probably is using <lib>.  You could use `solr/configsets/minimal.conf`

**Comment by tmortagne** [comment]
Unit test added following TestConfig#testLib() but with a different config.

**Comment by dsmiley** [comment]
Excellent.  Please add to solr/CHANGES.txt in the 8.8 bug fix section at the end, the following:
```
* SOLR-15017: Core lib directories were not being recognized unless the solrconfig included a <lib> directive.
  (Thomas Mortagne)
```
Meaningwhile I'm running all tests...

**Comment by tmortagne** [comment]
Fix the conflict with solr/CHANGES.txt.

**Pull request merged**
