### PR TITLE
SOLR-14189 switch from String.trim() to StringUtils.isBlank()

### PR DESCRIPTION
**Pull request by andywebb1975**
# Description

The edismax and some other query parsers treat pure whitespace queries as empty queries, but they use Java's String.trim() method to normalise queries. That method only treats characters 0-32 as whitespace. Other whitespace characters exist - such as U+3000 IDEOGRAPHIC SPACE - which bypass the test and lead to 400 Bad Request responses.

# Solution

This PR switches from String.trim() to StringUtils.isBlank() which is aware of all whitespace characters.

# Tests

I've added a test which sends U+3000 IDEOGRAPHIC SPACE and checks that it behaves the same way as U+0020 SPACE.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [ ] (not sure!) I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `master` branch.
- [x] I have run `ant precommit` and the appropriate test suite.
- [x] I have added tests for my changes.
- [ ] (n/a) I have added documentation for the [Ref Guide](https://github.com/apache/lucene-solr/tree/master/solr/solr-ref-guide) (for Solr changes only).

### CODE REVIEW

**Comment by uschindler** [comment]
Why not use the much more efficient StringUtils.isWhitespace() for the cases where the result is just checked for null? Just stripping and throwing away the result looks inefficient.

**Comment by andywebb1975** [comment]
That makes total sense, yes! I started out looking for something to replace String.trim() and stopped looking once I'd found StringUtils.stripToNull(). I'll update this to use StringUtils.isWhitespace() instead.

**Comment by andywebb1975** [comment]
I've made that change - it behaves the same as when I was using stripToNull() on my local instance.

**Comment by cpoerschke** [comment]
> ... String.trim() ... StringUtils.stripToNull() ... StringUtils.isWhitespace() ...

I wonder if `StringUtils.isBlank()` might be another option:

```
- if (val == null || StringUtils.isWhitespace(val) ) {
+ if (StringUtils.isBlank(val)) {
```

Not sure about `StringUtils.isWhitespace` vs. `StringUtils.isBlank` efficiency considerations though e.g. https://github.com/apache/lucene-solr/blob/releases/lucene-solr/8.4.1/solr/core/src/java/org/apache/solr/search/SwitchQParserPlugin.java#L166 uses it.

**Comment by uschindler** [comment]
IsBlank() is behaving fine. If you look at its source code all is checked:
- null means blank
- empty means blank
- all remaining characters are tested on isWhitespace()

So this is the best replacement. We should also look for similar patterns at other places in Solr.

+1

**Comment by andywebb1975** [comment]
hi Christine - thanks for looking at this, and for the tip! I've made the change to use `StringUtils.isBlank()`, which efficiency-wise looks just the same as `isWhitespace()` to me.

**Comment by andywebb1975** [comment]
I previously did a quick grep looking for `.trim(` and found these three instances that were obvious ones to change. The edismax instance is biting us as we get occasional exceptions in production due to junk queries, so that was my priority. There are lots more that could change, though I suspect they're much less likely to receive other unusual whitespace chars than the query parsers.

**Pull request merged**
