### PR TITLE
LUCENE-9685: Hunspell: prefix condition is only checked on suffix, not stem

### PR DESCRIPTION
**Pull request by donnerpeter**
# Description

aff:
```
PFX h Y 1
PFX h 0 de .

SFX A Y 1
SFX A te tion/S .
```
dic:
```
hydrate/hA
```
should pass: `assertStemsTo("dehydration", "hydrate");`

# Solution

After the prefix is stripped and there's a suffix to strip, its condition flag may be present not only on the suffix, but also on the stem.

# Tests

A synthetic test based on Spanish `deshidratación`

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `master` branch.
- [x] I have run `./gradlew check`.
- [x] I have added tests for my changes.
- [ ] I have added documentation for the [Ref Guide](https://github.com/apache/lucene-solr/tree/master/solr/solr-ref-guide) (for Solr changes only).

### CODE REVIEW

**Comment by donnerpeter** [comment]
Reviewing commits separately might be easier. Committing them separately might make sense (not so sure about that)

**Comment by dweiss** [comment]
Since it's an actual bug fix, add a separate changes entry under the right section? :)

**Comment by donnerpeter** [comment]
> Since it's an actual bug fix, add a separate changes entry under the right section? :)

I can but I'm not sure that'll be necessary. In the end, I imagine `CHANGES.txt` having just one entry like "LUCENE-XXXX *(maybe many issues)*: Hunspell: introduce SpellChecker API, fully English, Spanish, French, *whatever else* dictionaries", where this change would nicely fall into Spanish section. This should summarize the changes pretty well, and wouldn't overburden the readers with too much detail. Does this make sense to you?

**Comment by dweiss** [comment]
I thought about it too. I think a nicer way to do it would be to create one umbrella (parent) jira issue and sub-issues or sub-tasks which you could then create pull requests against. Or even skip sub-issues and just reference the parent directly from multiple PRs?

**Comment by donnerpeter** [comment]
The umbrella issue idea looks good, I can file one. Is "Hunspell SpellChecker API" or "Hunspell improvements" a good name?

As for skipping sub-issues, I'd be fine with that, but Robert Muir preferred them: http://mail-archives.apache.org/mod_mbox/lucene-dev/202101.mbox/%3CCAOdYfZXo-z5sy7LG_VCAQ-qj2_tM41sNw2E6ZzEDivwaDmDJDw%40mail.gmail.com%3E

**Comment by dweiss** [comment]
"Hunspell improvements" sounds great to me. You could even collect all the issues you've created so far and convert them to sub-tasks of that parent. (I think you should be able to do it; if not, let me know and I'll do it).

**Comment by donnerpeter** [comment]
I've filed https://issues.apache.org/jira/browse/LUCENE-9687 and will add my issues there.
Anything else in this PR?

**Comment by dweiss** [comment]
Nope, I think it looks good!

**Pull request merged**
