### PR TITLE
Improve how Asserting* classes handle singleton doc values.

### PR DESCRIPTION
**Pull request by jtibshirani**
Some queries use DocValues.unwrapSingleton to execute different logic for
single-valued doc values. When tests use AssertingCodec or AssertingLeafReader,
unwrapSingleton will never unwrap the doc values, as they don't have the
expected class. So some queries have code paths that are never exercised with
these asserting wrappers.

This change makes sure to preserve the expected classes when creating asserting
doc values.

### CODE REVIEW

**Comment by jtibshirani** [comment]
I noticed this when debugging a bad bug in `IndexSortSortedNumericDocValuesRangeQuery` that wasn't caught by tests. As a follow-up I plan to make at least one more testing fix, and also fix `IndexSortSortedNumericDocValuesRangeQuery` itself.

**Review by jpountz — APPROVED** [review]
This looks good to me.

**Comment by jtibshirani** [comment]
Thanks for the review. Let me know if I should add a changelog entry or issue number (I wasn't sure what to do for smaller test fixes like this).

**Comment by jpountz** [comment]
Good question. The test framework is used by our users so I think it makes sense to mention this change in the changelog.

**Pull request merged**
