### PR TITLE
SOLR-13926

### PR DESCRIPTION
**Pull request by millerjeff0**
# Description

Trying to improve documentation around mystical classes

# Solution

javadoc

# Tests

Committers eyes

# Checklist

Please review the following and check all that apply:

- [ x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x ] I have created a Jira issue and added the issue ID to my pull request title.
- [x ] I am authorized to contribute this code to the ASF and have removed any code I do not have a license to distribute.
- [ ] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x ] I have developed this patch against the `master` branch.
- [x ] I have run `ant precommit` and the appropriate test suite.
- [Z ] I have added tests for my changes.
- [X ] I have added documentation for the [Ref Guide](https://github.com/apache/lucene-solr/tree/master/solr/solr-ref-guide) (for Solr changes only).

### CODE REVIEW

**Comment by millerjeff0** [comment]
@yonik  Can you take a look

**Comment by dsmiley** [comment]
Cool.

In addition, I find the method contracts to the methods on DocRouter and it's subclasses highly unspecified (no javadocs or don't specify this).  In particular, it's not evident when a id/shardKey/routeKey param  is assumed to be the prefix, or assumed to be the prefix plus exclamation, or prefix+!+theRest or some combinations only or whatever.  It makes reasoning about what a method should do difficult.

**Comment by millerjeff0** [comment]
Yeah I’ll take a shot at method docs next, don’t merge this yet I wanted to get the class doc out for review first.

**Comment by dsmiley** [comment]
The class level docs are very helpful!  I think hold off on the method level docs.  I have a contribution pending locally that I wish to share here that adds _some_ method level docs.  @yonik what do you think of Jeff's docs here?

**Comment by yonik** [comment]
It's verbose (including the use of binary over hex ;-) but fine I think.
Since you have something else pending @dsmiley , I'll let you commit when you're ready.

**Pull request closed without merging**
