### PR TITLE
SOLR-16626: Upgrade to Netty 4.1.87.Final

### PR DESCRIPTION
**Pull request by janhoy**
Backport from 9.x

### CODE REVIEW

**Comment by itygh** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Review by risdenk — CHANGES_REQUESTED** [review]
missing solr/CHANGES.txt entry?

**Comment by janhoy** [comment]
> missing solr/CHANGES.txt entry?

That's right. I added it on the same line as the previous upgrade from SOLR-16424, keeping both JIRA-numbers. Do you think we should just mention this last one?

**Review by risdenk — APPROVED** [review]
Didn't run any tests or builds but looks good.

**Comment by janhoy** [comment]
Ran the entire test suite. Looks good.

**Pull request merged**
