### PR TITLE
SOLR-12276 

### PR DESCRIPTION
**Pull request by jdyer1**
SOLR-12276 
This pull request is a start.  Done so far:

- Menus
- Dashboard tab
- Collections tab (not finished)
- "ant server"

### CODE REVIEW

**Comment by dataminion** [comment]
How is this going is there anything I can help with here?

**Comment by jdyer1** [comment]
@dataminion , Feel free to jump in.  I am an absolute beginner with Angular (new & old) and Typescript, but thought this would be a good learning project.  So far I've done a fairly rote conversion of:

- Dashboard
- Collections Overview
- Analysis
- Dataimport Handler

There's a lot to go and I've been working here and there as time allows.  Certainly if this is going to be finished anytime soon, we need more help.  You also, if you've got the experience, can evaluate my approach here and see if any changes need to be made on that end.

**Comment by dataminion** [comment]
I've got some updates to your branch out on my fork. I am bringing the codebase into line with the more structured Angular standard. I also updated all the configs so that it will bootstrap with the new version of Angular Cli which I would definitely describe as more feature complete than the that was in your PR. Additionally I have been doing some refactoring to pull all of the core services into a solr-client lib this could later be published as a starting point for anyone else wanting to use the Admin api's within other Angular projects

**Comment by dataminion** [comment]
I am also pretty comfortable picking up the work for the data import handler I have done lots of work with those API's on another project.  It is probably what I will do once I am done refactoring.

**Comment by itygh** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Pull request closed without merging**
