### PR TITLE
SOLR-14932: Broken "Add replica" button in solr admin UI

### PR DESCRIPTION
**Pull request by poke19962008**
Earlier with solr 8.6.x drop down button to check live nodes got broken. 
image

### CODE REVIEW

**Comment by epugh** [comment]
I was messing with this yesterday, and I could t get the css to work!   This is much better.   I will test and merge.

**Comment by poke19962008** [comment]
also @epugh is it possible to add "hacktoberfest-accepted" label to this PR?

**Comment by epugh** [comment]
Definilty @poke19962008, we have another PR that has that label.  Keep em coming!

**Comment by epugh** [comment]
closing since these improvements were merged in #1988.    Thank you @poke19962008 for the fix, and let me know if I need to do something to make sure you get your Hacktoberfest points!   Can't wait for more Admin UI fixes.

**Pull request closed without merging**
