### PR TITLE
Backport LUCENE-9948 LUCENE-9964

### PR DESCRIPTION
**Pull request by gautamworah96**
This PR backports LUCENE-9948 (Automatically detect multi and single valued..) and LUCENE-9964 (Duplicate long values ...).

Backporting just LUCENE-9964 was difficult to achieve without backporting the changes made by LUCENE-9948 in `LongValueFacetCounts` (and would've messed up the code!).

Note to reviewers:
I had to make an extra change f10ca3a (apart from the backport commits) to get `ant test` running.
Apart from that all changes are pretty much `cherry-pick`ed from upstream.   

There was some concern about maintaining backwards compatibility in the LUCENE-9948 JIRA (as it removes a param). Is it fine if we change the API in the new Lucene 8.10 version?

### CODE REVIEW

**Comment by gautamworah96** [comment]
tag @rmuir @gsmiller @mikemccand (need some reviewer eyes)

**Comment by gsmiller** [comment]
@gautamworah96 I don't think we want to make this non-backwards compatible change (LUCENE-9948) in 8.10. I think we need to wait for 9.0 for that. This is just what I've gathered from having a look at [this doc](https://cwiki.apache.org/confluence/display/LUCENE/BackwardsCompatibility). Maybe give it a read and let me know if you interpret differently?

**Comment by mikemccand** [comment]
> @gautamworah96 I don't think we want to make this non-backwards compatible change (LUCENE-9948) in 8.10. I think we need to wait for 9.0 for that. This is just what I've gathered from having a look at [this doc](https://cwiki.apache.org/confluence/display/LUCENE/BackwardsCompatibility). Maybe give it a read and let me know if you interpret differently?

Usually what we do is deprecate the old API and keep it (on backport), pointing to the new API.  This way there is no API break, just a new deprecation.  Can that work here?

**Comment by gsmiller** [comment]
I'm a bit skeptical of needing to backport both of these changes together to be honest. For LUCENE-9948, I think the easiest/best thing to do is to let it be a breaking change with 9.0 and not worry too much about trying to introduce it earlier. @gautamworah96 my recollection is that the change in LUCENE-9964 was fairly straight-forward, and it seems to me like it could be backported on its own without needing to tangle in changes from LUCENE-9948. Is that not the case?

**Comment by gautamworah96** [comment]
@gsmiller Yes. I think the change is simple enough to be coded manually. Git did not allow direct cherry picking due to conflicts and that is why I suggested that I backport the other change as well. I'll revise it

**Comment by gsmiller** [comment]
Hey @gautamworah96 I went ahead and took care of this backport along with another one that needed to be pulled in. Since it was pretty simple, it was easy to just do while I was there. Thanks again for working on this fix!

**Pull request closed without merging**
