### PR TITLE
SOLR-14328:HdfsDirectory support createTempOutput

### PR DESCRIPTION
**Pull request by kaynewu**
Description:
See https://issues.apache.org/jira/browse/SOLR-14328
HdfsDirectory support createTempOutput

### CODE REVIEW

**Comment by janhoy** [comment]
@kaynewu Have you opened a JIRA issue as well for this?

**Comment by kaynewu** [comment]
> @kaynewu Have you opened a JIRA issue as well for this?

sorry for the late reply， I have opened a JIRA for this problem，Please check when you are convenient， thank you so much.

**Comment by risdenk** [comment]
@kaynewu I think this was already resolved in SOLR-14242?  It was fixed around around the same time this PR was opened.

**Comment by risdenk** [comment]
Duplicate of SOLR-14242

**Pull request closed without merging**
