### PR TITLE
SOLR-11622: Fix mime4j library dependency for Tika

### PR DESCRIPTION
**Pull request by mrkarthik**

### CODE REVIEW

**Comment by mrkarthik** [comment]
For some reason this pull request is not getting updated, created new pull request https://github.com/apache/lucene-solr/pull/282

**Comment by tballison** [comment]
This was the patch I had before running ant precommit, etc., which is still running.  You'll need to run ant-
clean-jars, jar-checksums and do the git add/rm before this will work.

[SOLR-11622_tallison.patch.txt](https://github.com/apache/lucene-solr/files/1528484/SOLR-11622_tallison.patch.txt)

**Comment by mrkarthik** [comment]
I had local branch solr-11622 and origin had SOLR-11622, for some reason my branch is getting deleted.
Sorry for the all these deletes.

**Comment by tballison** [comment]
[SOLR-11622-tallison.diff.txt](https://github.com/apache/lucene-solr/files/1528516/SOLR-11622-tallison.diff.txt)

This is the full `git diff 83753d0..d2f40af > SOLR-11622-tallison.diff`

Had to add jackcess-encrypt for msaccess, bcpkix for psd files, and rome-utils for atom/rss.

**Pull request closed without merging**
