### PR TITLE
SOLR-14358 Document how to use Processor in JavaDocs

### PR DESCRIPTION
**Pull request by epugh**
# Description

There is an existing PR (https://github.com/apache/lucene-solr/pull/404) from 2018 that needed some updates to the JavaDoc formatting.

# Solution

I fixed the formatting.

# Tests

ran `ant documentation`

# Checklist

Please review the following and check all that apply:

- [ X] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of myx ability.
- [ x] I have created a Jira issue and added the issue ID to my pull request title.
- [ X] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [ X] I have developed this patch against the `master` branch.
- [ X] I have run `ant precommit` and the appropriate test suite.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Ref Guide](https://github.com/apache/lucene-solr/tree/master/solr/solr-ref-guide) (for Solr changes only).

### CODE REVIEW

**Comment by janhoy** [comment]
Great! Just wonder if this doc would also fit in the RefGuide? Users will not always care about java docs.

In the example, it would be better if the url_xxx fields were defined as single valued and numeric where it makes sense. A typical use case is to use these for various query boosts. Perhaps that should be mentioned too?

**Comment by HoustonPutman** [comment]
The [URP refguide page](https://lucene.apache.org/solr/guide/8_4/update-request-processors.html#general-use-updateprocessorfactories) links to each of the individual processors' Javadocs. So for now I don't see an issue with this documentation living in the Javadocs, until the documentation for all the processors gets mass-migrated to the ref-guide.

**Comment by epugh** [comment]
So @janhoy and @HoustonPutman is there something you want me to change?  Should I tackle the `url_xxx` naming?

**Comment by janhoy** [comment]
Yes, please use single valued int fields for url_length , url_levels , url_toplevel and url_landingpage
Else, it looks good!

**Comment by epugh** [comment]
@janhoy and @HoustonPutman I'm trying to untangle some glitches, including finalizing the input you gave me on this PR.   I am changing in a new branch the singled valued int fields feedback.

**Comment by epugh** [comment]
Closing this in favor of https://github.com/apache/lucene-solr/pull/1632 as part of this was already committed.

**Pull request closed without merging**
