### PR TITLE
SOLR-14905: Update commons-io version to 2.8.0

### PR DESCRIPTION
**Pull request by NazerkeBS**
# Description

Please provide a short description of the changes you're making with this pull request.

# Solution

Please provide a short description of the approach taken to implement your solution.

# Tests

Please describe the tests you've developed or run to confirm this patch implements the feature or solves the problem.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [ ] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `master` branch.
- [x] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Ref Guide](https://github.com/apache/lucene-solr/tree/master/solr/solr-ref-guide) (for Solr changes only).

### CODE REVIEW

**Review by bruno-roustant — APPROVED** [review]

**Comment by ErickErickson** [comment]
This will not update 8x. We switched to Gradle for master only, backporting to a different build system partway through the 8x code line didn't seem wise. 

On 8x, you need to change lucene/ivy-versions.properties and run at least "ant jar-checksums" along with running precommit and the full test suite...

**Comment by bruno-roustant** [comment]
Good point Erick. I think the plan was mainly to upgrade master, but that would be nice to also upgrade 8x.
@NazerkeBS would you like to create a second PR (separate from this one) for 8x? Otherwise I'll do it.

**Review by juanka588 — APPROVED** [review]

**Comment by ErickErickson** [comment]
I don't insist on backporting to 8x, just making sure it's on people's radar if people want to backport...

**Comment by NazerkeBS** [comment]
I will backport this change to 8x with new PR.

**Comment by NazerkeBS** [comment]
@bruno-roustant, the second PR for backporting this change to 8x: https://github.com/apache/lucene-solr/pull/1935

**Pull request closed without merging**
