### PR TITLE
Comment to explain how to use URLClassifyProcessorFactory

### PR DESCRIPTION
**Pull request by ohtwadi**
URLClassifyProcessorFactory didn't have even a basic example on how to use this. I've added that now.

### CODE REVIEW

**Comment by tflobbe** [comment]
This looks useful, however the javadoc is not well formatted, not according to our validation at least. If you call `ant validate` at the top level you should see the errors and warnings.

**Comment by janhoy** [comment]
@ohtwadi Do you want to address the review comment so we can merge this?

**Comment by epugh** [comment]
@janhoy I went ahead and made the changes to @ohtwadi original PR, and it's available at https://github.com/apache/lucene-solr/pull/1372.   I think you can close this PR in favor of #1372 !

**Comment by epugh** [comment]
Closing this in favor of #1632

**Pull request closed without merging**
