### PR TITLE
Make testLUCENE8736 Check For Async Caching

### PR DESCRIPTION
**Pull request by atris**
Allow testLUCENE8736 to wait for async caching query loads

### CODE REVIEW

**Comment by atris** [comment]
Ran `ant beast -Dbeast.iters=20 -Dtests.dups=6  -Dtestcase=TestLatLonShape -Dtests.method=testLUCENE8736* -Dtests.seed=D784C9A46B62FB84 -Dtests.slow=true -Dtests.badapples=true -Dtests.locale=brx -Dtests.timezone=America/Guatemala -Dtests.asserts=true`

Came in clean

**Comment by atris** [comment]
precommit fails due to errors from `MockInitialContextFactory.java`

**Comment by iverase** [comment]
I don't think we should do that, caching the query should not affect the result of the query.

**Comment by iverase** [comment]
And there are other test failing for the same reason, see:

https://elasticsearch-ci.elastic.co/job/apache+lucene-solr+master/5609/console

**Comment by atris** [comment]
I see, I will investigate the other test and reopen the PR

**Pull request closed without merging**
