### PR TITLE
Wipe content of `branch_8x` to prevent accidental commits.

### PR DESCRIPTION
**Pull request by jpountz**

### CODE REVIEW

**Comment by msokolov** [comment]
Files changed: 5000+ !!

**Review by msokolov — APPROVED** [review]
-2,600,714 lines - this is making github quite slow :)

**Comment by uschindler** [comment]
I think the reference to main and 9.x should possibly better be a link to the new Lucene repository.

**Review by uschindler — APPROVED** [review]

**Comment by uschindler** [comment]
thanks! Looks fine.

**Comment by uschindler** [comment]
I think the githib workflow needs to be removed in lucene-solr/master, too. But that's plain simple separate commit. We may try it out if it still triggers or not. I am always unsure where github picks the settings from.

**Comment by uschindler** [comment]
On master branch is also a reference to branch_8x, should possibly also removed. I can do this later when this is merged.

**Comment by uschindler** [comment]
I committed a6dcef49314a2651a5838c2b4ab2263aac69cd36 and 860a9dbd42d1bfb021688bd40ded58d38dedaf8b in master.

**Pull request merged**
