### PR TITLE
fixed some CSS syntax errors in Solr webapp

### PR DESCRIPTION
**Pull request by saschaszott**

### CODE REVIEW

**Comment by arafalov** [comment]
Is there a JIRA connected to this? Also, I see code but not description of the problem/effect. Was some CSS not working and this fixes it?

**Comment by saschaszott** [comment]
Indeed, there is no JIRA issue directly related to this pull request. My IDE was just complaining about those CSS files.

**Comment by arafalov** [comment]
Ok. I will incorporate them the next time I am updating Admin UI (couple of weeks from now, most likely).

Thank you for the contribution.

**Comment by tflobbe** [comment]
These changes were fixed as part of 
https://github.com/apache/lucene-solr/pull/541

**Pull request closed without merging**
