### PR TITLE
Found that asciidoctor 1.5.6.2 cause build-site to fail on long anchors

### PR DESCRIPTION
**Pull request by gus-asf**
Documenting need to have ascii doctor version up to date.

### CODE REVIEW

**Comment by ctargett** [comment]
This is only a problem if you already had it installed before it was upgraded several months ago. At that time, I sent mail to the Dev list explaining the need for people to specifically upgrade, and it’s explained in the Jira issue I used at that time. I’m on vacation, so I’ll leave searching for those things up to you. For people who never installed any of the dependencies, I believe the right version of the gem gets installed with jekyll-asciidoc gem, it just doesn’t upgrade it if you already have it, which is why I’d removed it from the README. And as soon as we move to Gradle, the need for any dependencies goes away entirely.

So what you choose to do with this PR with all that info is up to you, but I’d prefer it be clear and accurate about who needs the extra step. As I mentioned, I’m on vacation, so won’t be reviewing this again until next week at the earliest.

**Comment by dweiss** [comment]
Please use gradle to compile the refguide. It'll keep dependencies up to date and consistent.

**Comment by gus-asf** [comment]
> Please use gradle to compile the refguide. It'll keep dependencies up to date and consistent.

This is a pull for 8x only. I am aware that gradle is managing deps for 9x :) a big improvment!

**Comment by gus-asf** [comment]
> This is only a problem if you already had it installed before it was upgraded several months ago. At that time, I sent mail to the Dev list explaining the need for people to specifically upgrade, and it’s explained in the Jira issue I used at that time. I’m on vacation, so I’ll leave searching for those things up to you. For people who never installed any of the dependencies, I believe the right version of the gem gets installed with jekyll-asciidoc gem, it just doesn’t upgrade it if you already have it, which is why I’d removed it from the README. And as soon as we move to Gradle, the need for any dependencies goes away entirely.
> 
> So what you choose to do with this PR with all that info is up to you, but I’d prefer it be clear and accurate about who needs the extra step. As I mentioned, I’m on vacation, so won’t be reviewing this again until next week at the earliest.

Ah, it seems I missed that email. It seems to have been in October last year and I was crazy busy with client work at that point with two projects trying to wrap up up simultaneously before Thanksgiving. I think it's probably good to have some note in the README for others who missed the email, or who perhaps only followed through on one computer, or on the odd chance someone used asciidoctor for something else previously. I will be clear that it's only necessary if asciidoctor is previously installed. I suspected you would have something to add here, and I appreciate the review, especially during your vacation. Sorry if this disrupted it, Enjoy!

**Pull request merged**
