### PR TITLE
LUCENE-9629: Use computed masks

### PR DESCRIPTION
**Pull request by gf2121**
# Description

In the class ForUtil, mask values have been computed and stored in static final vailables, but they are recomputed for each encoding, maybe we can avoid this~

# Solution

use the computed mask values

### CODE REVIEW

**Review by jpountz — APPROVED** [review]

**Comment by dweiss** [comment]
I wonder if the difference in performance is observable since final long values would be inlined at compile time (and easily optimized for hotspot) whereas array accesses, even if locally cached, still have to be dynamic (I don't think the compiler is smart enough to detect constant array values?).

**Comment by gf2121** [comment]
Thank you for your reply @dweiss ! This is indeed something to worry about, so a silly benchmark between const values and const arrays had been run before i submited this commit:
```
public class Main {
    private static final long NANO_2_MILL = 1000000;
    private static final int TIMES = 100;
    public static void main(String[] args) throws Exception {
        //use static final longs
//        ForUtil forUtil = new ForUtilWithConstValues();
        //use static final arrays
        ForUtil forUtil = new ForUtilWithConstArrays();
        System.out.println(forUtil.getClass().getName());
        DataInput dataInput = new DataInput() {
            @Override
            public byte readByte() throws IOException { return 0; }
            @Override
            public void readBytes(byte[] bytes, int i, int i1) throws IOException {}
            @Override
            public void readLELongs(long[] dst, int offset, int length) throws IOException {
                Arrays.fill(dst, offset, offset + length, 1L);
            }
        };
        long[] nums = new long[128];
        for (int i = 0; i < 100000000; i++) {
            forUtil.decode(1, dataInput, nums);
        }
        System.out.println("warmed");
        long best = Long.MAX_VALUE;
        long worst = 0L;
        long sum = 0L;
        for (int time = 0; time < TIMES; time++) {
            long start = System.nanoTime();
            for (int i = 0; i < 50000000; i++) {
                forUtil.decode(1, dataInput, nums);
            }
            long end = System.nanoTime();
            long took = end - start;
            sum += took;
            if (took < best) {
                best = took;
            } else if (took > worst) {
                worst = took;
            }
        }
        System.out.println(String.format("best: %d ms, worst: %d ms, avg: %d ms", best/NANO_2_MILL, worst/NANO_2_MILL, sum/NANO_2_MILL/TIMES));
    }
}
```

And here is the result:

> org.apache.lucene.codecs.lucene84.ForUtilWithConstValues
> warmed
> best: 1275 ms, worst: 1480 ms, avg: 1326 ms
> 
> org.apache.lucene.codecs.lucene84.ForUtilWithConstArrays
> warmed
> best: 1263 ms, worst: 1488 ms, avg: 1328 ms

The result looks good to me, but i'm not sure if it makes sense to you. If there are other jobs needed on the point, just tell me~

**Comment by dweiss** [comment]
Microbenchmarks can be tricky... here I think the optimizer can remove a lot of the code because the results of those computations are not stored anywhere. A JMH benchmark would be better, anyway - Mike has this tool that provides a somewhat more realistic data so we should see the difference in the long run.

https://home.apache.org/~mikemccand/lucenebench/

**Comment by dweiss** [comment]
Thanks for satisfying my curiosity!

**Comment by gf2121** [comment]
There are still several `mask32()` called in `decodeSlow()`,  I have fixed it in the newest commit and checked again to make sure that `mask8()`, `mask16()` and `mask32()` are only called in the `static{}` code block.

**Comment by gf2121** [comment]
> I wonder if the difference in performance is observable since final long values would be inlined at compile time (and easily optimized for hotspot) whereas array accesses, even if locally cached, still have to be dynamic (I don't think the compiler is smart enough to detect constant array values?).

Hi @dweiss ! Thers days I did some more benchmarks on this issue and get some 'amazing' result...
First, i randomly choosed a decode method `decode15`, and try to find out if it will be slower in an array case. Here is the benchmark code based on JMH:
```
@State(Scope.Benchmark)
public class MyBenchmark {
    private static final long MASK16_1 = 0x0001000100010001L;
    private static final long[] MASKS16_1 = new long[] {MASK16_1};
    private static final long[] TMP = new long[128];
    private static final long[] ARR = new long[128];

    static {
        for (int i=0;i<128;i++) {
            TMP[i] = ARR[i] = i;
        }
    }

    public static void main(String[] args) throws RunnerException {
        Options opt = new OptionsBuilder()
                .include("MyBenchmark")
                .build();

        new Runner(opt).run();
    }

    @Benchmark
    @BenchmarkMode({Mode.Throughput})
    @Fork(1)
    @Measurement(iterations = 10, time = 1, timeUnit = TimeUnit.SECONDS)
    @Warmup(iterations = 3, time = 1, timeUnit = TimeUnit.SECONDS)
    public static void decode0() {
        for (int iter = 0, tmpIdx = 0, longsIdx = 30; iter < 2; ++iter, tmpIdx += 15, longsIdx += 1) {
            long l0 = (TMP[tmpIdx+0] & MASKS16_1[0]) << 14;
            l0 |= (TMP[tmpIdx+1] & MASKS16_1[0]) << 13;
            l0 |= (TMP[tmpIdx+2] & MASKS16_1[0]) << 12;
            l0 |= (TMP[tmpIdx+3] & MASKS16_1[0]) << 11;
            l0 |= (TMP[tmpIdx+4] & MASKS16_1[0]) << 10;
            l0 |= (TMP[tmpIdx+5] & MASKS16_1[0]) << 9;
            l0 |= (TMP[tmpIdx+6] & MASKS16_1[0]) << 8;
            l0 |= (TMP[tmpIdx+7] & MASKS16_1[0]) << 7;
            l0 |= (TMP[tmpIdx+8] & MASKS16_1[0]) << 6;
            l0 |= (TMP[tmpIdx+9] & MASKS16_1[0]) << 5;
            l0 |= (TMP[tmpIdx+10] & MASKS16_1[0]) << 4;
            l0 |= (TMP[tmpIdx+11] & MASKS16_1[0]) << 3;
            l0 |= (TMP[tmpIdx+12] & MASKS16_1[0]) << 2;
            l0 |= (TMP[tmpIdx+13] & MASKS16_1[0]) << 1;
            l0 |= (TMP[tmpIdx+14] & MASKS16_1[0]) << 0;
            ARR[longsIdx+0] = l0;
        }
    }

    @Benchmark
    @BenchmarkMode({Mode.Throughput})
    @Fork(1)
    @Measurement(iterations = 10, time = 1, timeUnit = TimeUnit.SECONDS)
    @Warmup(iterations = 3, time = 1, timeUnit = TimeUnit.SECONDS)
    public static void decode1() {
        for (int iter = 0, tmpIdx = 0, longsIdx = 30; iter < 2; ++iter, tmpIdx += 15, longsIdx += 1) {
            long l0 = (TMP[tmpIdx+0] & MASK16_1) << 14;
            l0 |= (TMP[tmpIdx+1] & MASK16_1) << 13;
            l0 |= (TMP[tmpIdx+2] & MASK16_1) << 12;
            l0 |= (TMP[tmpIdx+3] & MASK16_1) << 11;
            l0 |= (TMP[tmpIdx+4] & MASK16_1) << 10;
            l0 |= (TMP[tmpIdx+5] & MASK16_1) << 9;
            l0 |= (TMP[tmpIdx+6] & MASK16_1) << 8;
            l0 |= (TMP[tmpIdx+7] & MASK16_1) << 7;
            l0 |= (TMP[tmpIdx+8] & MASK16_1) << 6;
            l0 |= (TMP[tmpIdx+9] & MASK16_1) << 5;
            l0 |= (TMP[tmpIdx+10] & MASK16_1) << 4;
            l0 |= (TMP[tmpIdx+11] & MASK16_1) << 3;
            l0 |= (TMP[tmpIdx+12] & MASK16_1) << 2;
            l0 |= (TMP[tmpIdx+13] & MASK16_1) << 1;
            l0 |= (TMP[tmpIdx+14] & MASK16_1) << 0;
            ARR[longsIdx+0] = l0;
        }
    }

    @Benchmark
    @BenchmarkMode({Mode.Throughput})
    @Fork(1)
    @Measurement(iterations = 10, time = 1, timeUnit = TimeUnit.SECONDS)
    @Warmup(iterations = 3, time = 1, timeUnit = TimeUnit.SECONDS)
    public static void decode2() {
        for (int iter = 0, tmpIdx = 0, longsIdx = 30; iter < 2; ++iter, tmpIdx += 15, longsIdx += 1) {
            long l0 = (TMP[tmpIdx+0] & 0x0001000100010001L) << 14;
            l0 |= (TMP[tmpIdx+1] & 0x0001000100010001L) << 13;
            l0 |= (TMP[tmpIdx+2] & 0x0001000100010001L) << 12;
            l0 |= (TMP[tmpIdx+3] & 0x0001000100010001L) << 11;
            l0 |= (TMP[tmpIdx+4] & 0x0001000100010001L) << 10;
            l0 |= (TMP[tmpIdx+5] & 0x0001000100010001L) << 9;
            l0 |= (TMP[tmpIdx+6] & 0x0001000100010001L) << 8;
            l0 |= (TMP[tmpIdx+7] & 0x0001000100010001L) << 7;
            l0 |= (TMP[tmpIdx+8] & 0x0001000100010001L) << 6;
            l0 |= (TMP[tmpIdx+9] & 0x0001000100010001L) << 5;
            l0 |= (TMP[tmpIdx+10] & 0x0001000100010001L) << 4;
            l0 |= (TMP[tmpIdx+11] & 0x0001000100010001L) << 3;
            l0 |= (TMP[tmpIdx+12] & 0x0001000100010001L) << 2;
            l0 |= (TMP[tmpIdx+13] & 0x0001000100010001L) << 1;
            l0 |= (TMP[tmpIdx+14] & 0x0001000100010001L) << 0;
            ARR[longsIdx+0] = l0;
        }
    }
}
```
**Result:**

> MyBenchmark.decode0  thrpt   10  107204513.594 ± 4773882.841  ops/s
> MyBenchmark.decode1  thrpt   10   68214347.208 ± 1293940.972  ops/s
> MyBenchmark.decode2  thrpt   10   67038804.906 ± 1667315.376  ops/s

Surprisingly, the static final array val get a more than 50% faster than static final long. I am not sure if there is anything wrong in the benchmark code, and not sure if the result make sense in a realistic scene. Most of all, please tell me if you have some clue for the reason:)

**Comment by madrob** [comment]
You need to either return a value from the benchmark methods or call blackhole.consume, otherwise the JVM will detect that everything is unused outside of the scope and optimize it away. That should get you some different results. Thank you for being thorough!

**Comment by gf2121** [comment]
> You need to either return a value from the benchmark methods or call blackhole.consume, otherwise the JVM will detect that everything is unused outside of the scope and optimize it away. That should get you some different results. Thank you for being thorough!

Thank you for the clue! Based on your guidance, I tried some more benchmark, but find array val is alway faster... here are the codes and results (code is used to shows the way that i tried to prevent jvm optimize, so only one method is enough).

1. return an array result
```
public long[] decode0() {
        for (int iter = 0, tmpIdx = 0, longsIdx = 30; iter < 2; ++iter, tmpIdx += 15, longsIdx += 1) {
            long l0 = (TMP[tmpIdx+0] & MASKS16_1[0]) << 14;
            l0 |= (TMP[tmpIdx+1] & MASKS16_1[0]) << 13;
            l0 |= (TMP[tmpIdx+2] & MASKS16_1[0]) << 12;
            l0 |= (TMP[tmpIdx+3] & MASKS16_1[0]) << 11;
            l0 |= (TMP[tmpIdx+4] & MASKS16_1[0]) << 10;
            l0 |= (TMP[tmpIdx+5] & MASKS16_1[0]) << 9;
            l0 |= (TMP[tmpIdx+6] & MASKS16_1[0]) << 8;
            l0 |= (TMP[tmpIdx+7] & MASKS16_1[0]) << 7;
            l0 |= (TMP[tmpIdx+8] & MASKS16_1[0]) << 6;
            l0 |= (TMP[tmpIdx+9] & MASKS16_1[0]) << 5;
            l0 |= (TMP[tmpIdx+10] & MASKS16_1[0]) << 4;
            l0 |= (TMP[tmpIdx+11] & MASKS16_1[0]) << 3;
            l0 |= (TMP[tmpIdx+12] & MASKS16_1[0]) << 2;
            l0 |= (TMP[tmpIdx+13] & MASKS16_1[0]) << 1;
            l0 |= (TMP[tmpIdx+14] & MASKS16_1[0]) << 0;
            ARR[longsIdx+0] = l0;
        }
        return ARR;
}
```
method | speed (ops/s)
------------ | -------------
MyBenchmark.decode0 | 92215691.271 ± 1149229.830
MyBenchmark.decode1 | 62019521.428 ± 4268837.164
MyBenchmark.decode2 | 62595196.347 ± 1434012.058

2. return an long result
```
public long decode0() {
        for (int iter = 0, tmpIdx = 0, longsIdx = 30; iter < 2; ++iter, tmpIdx += 15, longsIdx += 1) {
            long l0 = (TMP[tmpIdx+0] & MASKS16_1[0]) << 14;
            l0 |= (TMP[tmpIdx+1] & MASKS16_1[0]) << 13;
            l0 |= (TMP[tmpIdx+2] & MASKS16_1[0]) << 12;
            l0 |= (TMP[tmpIdx+3] & MASKS16_1[0]) << 11;
            l0 |= (TMP[tmpIdx+4] & MASKS16_1[0]) << 10;
            l0 |= (TMP[tmpIdx+5] & MASKS16_1[0]) << 9;
            l0 |= (TMP[tmpIdx+6] & MASKS16_1[0]) << 8;
            l0 |= (TMP[tmpIdx+7] & MASKS16_1[0]) << 7;
            l0 |= (TMP[tmpIdx+8] & MASKS16_1[0]) << 6;
            l0 |= (TMP[tmpIdx+9] & MASKS16_1[0]) << 5;
            l0 |= (TMP[tmpIdx+10] & MASKS16_1[0]) << 4;
            l0 |= (TMP[tmpIdx+11] & MASKS16_1[0]) << 3;
            l0 |= (TMP[tmpIdx+12] & MASKS16_1[0]) << 2;
            l0 |= (TMP[tmpIdx+13] & MASKS16_1[0]) << 1;
            l0 |= (TMP[tmpIdx+14] & MASKS16_1[0]) << 0;
            ARR[longsIdx+0] = l0;
        }
        return ARR[31];
}
```
method | speed (ops/s)
------------ | -------------
MyBenchmark.decode0 | 92470935.234 ± 3525240.576
MyBenchmark.decode1 | 62389057.277 ±  567747.489
MyBenchmark.decode2 | 62141559.925 ± 1012364.417

3. blackwhole consume last
```
public void decode0(Blackhole blackhole) {
        for (int iter = 0, tmpIdx = 0, longsIdx = 30; iter < 2; ++iter, tmpIdx += 15, longsIdx += 1) {
            long l0 = (TMP[tmpIdx+0] & MASKS16_1[0]) << 14;
            l0 |= (TMP[tmpIdx+1] & MASKS16_1[0]) << 13;
            l0 |= (TMP[tmpIdx+2] & MASKS16_1[0]) << 12;
            l0 |= (TMP[tmpIdx+3] & MASKS16_1[0]) << 11;
            l0 |= (TMP[tmpIdx+4] & MASKS16_1[0]) << 10;
            l0 |= (TMP[tmpIdx+5] & MASKS16_1[0]) << 9;
            l0 |= (TMP[tmpIdx+6] & MASKS16_1[0]) << 8;
            l0 |= (TMP[tmpIdx+7] & MASKS16_1[0]) << 7;
            l0 |= (TMP[tmpIdx+8] & MASKS16_1[0]) << 6;
            l0 |= (TMP[tmpIdx+9] & MASKS16_1[0]) << 5;
            l0 |= (TMP[tmpIdx+10] & MASKS16_1[0]) << 4;
            l0 |= (TMP[tmpIdx+11] & MASKS16_1[0]) << 3;
            l0 |= (TMP[tmpIdx+12] & MASKS16_1[0]) << 2;
            l0 |= (TMP[tmpIdx+13] & MASKS16_1[0]) << 1;
            l0 |= (TMP[tmpIdx+14] & MASKS16_1[0]) << 0;
            ARR[longsIdx+0] = l0;
        }
        blackhole.consume(ARR[30]);
        blackhole.consume(ARR[31]);
}
```
method | speed (ops/s)
------------ | -------------
MyBenchmark.decode0 | 79570016.826 ± 1210338.335
MyBenchmark.decode1 | 58225242.201 ±  905039.184
MyBenchmark.decode2 | 58524381.688 ±  585220.494

4. blackwhole consume in loop
```
public void decode0(Blackhole blackhole) {
        for (int iter = 0, tmpIdx = 0, longsIdx = 30; iter < 2; ++iter, tmpIdx += 15, longsIdx += 1) {
            long l0 = (TMP[tmpIdx+0] & MASKS16_1[0]) << 14;
            l0 |= (TMP[tmpIdx+1] & MASKS16_1[0]) << 13;
            l0 |= (TMP[tmpIdx+2] & MASKS16_1[0]) << 12;
            l0 |= (TMP[tmpIdx+3] & MASKS16_1[0]) << 11;
            l0 |= (TMP[tmpIdx+4] & MASKS16_1[0]) << 10;
            l0 |= (TMP[tmpIdx+5] & MASKS16_1[0]) << 9;
            l0 |= (TMP[tmpIdx+6] & MASKS16_1[0]) << 8;
            l0 |= (TMP[tmpIdx+7] & MASKS16_1[0]) << 7;
            l0 |= (TMP[tmpIdx+8] & MASKS16_1[0]) << 6;
            l0 |= (TMP[tmpIdx+9] & MASKS16_1[0]) << 5;
            l0 |= (TMP[tmpIdx+10] & MASKS16_1[0]) << 4;
            l0 |= (TMP[tmpIdx+11] & MASKS16_1[0]) << 3;
            l0 |= (TMP[tmpIdx+12] & MASKS16_1[0]) << 2;
            l0 |= (TMP[tmpIdx+13] & MASKS16_1[0]) << 1;
            l0 |= (TMP[tmpIdx+14] & MASKS16_1[0]) << 0;
            blackhole.consume(l0);
            ARR[longsIdx+0] = l0;
        }
}
```
method | speed (ops/s)
------------ | -------------
MyBenchmark.decode0 | 62292723.905 ± 185021.358
MyBenchmark.decode1 | 43453980.399 ± 645575.911
MyBenchmark.decode2 | 43369008.884 ± 751782.611

**Comment by dweiss** [comment]
Short of dumping the assembly code and seeing what's going on there's not much I can help you with, sorry! I'd  Remember that optimizations such as this one are really short-lived if isolated from the rest of the code - the optimizer will take part of your code and inline it with other code, then rearrange everything and put it through an optimizer... it's really hard to predict what's going to be left at the end.

On the surface it looks like array accesses are hoisted and reused (loaded in a register probably) while the constant is always inlined as part of the instruction... it's really guessing though.

I love low-level benchmarks but the ultimate test is a high-level use case (such as Mike's wikipedia indexing benchmark) where the pipeline is used end-to-end.

**Comment by jpountz** [comment]
@gf2121 do you plan on running a full benchmark as a next step?

**Comment by gf2121** [comment]
> @gf2121 do you plan on running a full benchmark as a next step?

@jpountz Hi! I am a bit confused about the meaning of `a full benchmark`. There has already been an end-to-end benchmark result on the forth floor to prove that this PR do no harm to reading performance. So i guess `a full benchmark` means an end-to-end benchmark after combining this PR and #2139 . If so, here is the result: 

```
                  IntNRQ      465.57      (9.7%)      450.01     (11.3%)   -3.3% ( -22% -   19%) 0.315
                 Prefix3      590.71      (9.8%)      589.66      (9.9%)   -0.2% ( -18% -   21%) 0.954
              HighPhrase      514.38      (6.9%)      513.57      (8.6%)   -0.2% ( -14% -   16%) 0.949
   BrowseMonthSSDVFacets      120.58      (3.7%)      120.39      (3.7%)   -0.2% (  -7% -    7%) 0.897
BrowseDayOfYearSSDVFacets      110.91      (3.0%)      111.05      (3.8%)    0.1% (  -6% -    7%) 0.904
                 MedTerm     2638.05      (5.3%)     2653.06      (6.9%)    0.6% ( -11% -   13%) 0.770
                PKLookup      249.12      (3.5%)      250.62      (3.0%)    0.6% (  -5% -    7%) 0.562
    HighIntervalsOrdered      197.05      (4.2%)      198.28      (3.6%)    0.6% (  -6% -    8%) 0.614
            HighSpanNear      290.39      (5.3%)      292.47      (3.5%)    0.7% (  -7% -   10%) 0.616
             MedSpanNear      111.25      (4.6%)      112.14      (3.4%)    0.8% (  -6% -    9%) 0.529
               OrHighLow      731.88      (8.3%)      740.55      (6.5%)    1.2% ( -12% -   17%) 0.614
               OrHighMed      347.73      (6.6%)      351.92      (6.2%)    1.2% ( -10% -   15%) 0.553
        HighSloppyPhrase       45.62      (5.9%)       46.30      (4.7%)    1.5% (  -8% -   12%) 0.379
               LowPhrase      150.50      (4.9%)      152.76      (3.6%)    1.5% (  -6% -   10%) 0.268
             LowSpanNear      611.34      (6.2%)      620.64      (4.5%)    1.5% (  -8% -   13%) 0.375
                 Respell      149.20      (5.2%)      151.54      (3.8%)    1.6% (  -7% -   11%) 0.276
               MedPhrase      576.79      (7.7%)      585.87      (4.5%)    1.6% (  -9% -   14%) 0.430
             AndHighHigh      269.78      (4.9%)      274.21      (3.4%)    1.6% (  -6% -   10%) 0.223
                HighTerm     1632.27      (6.0%)     1659.51      (6.2%)    1.7% (  -9% -   14%) 0.384
         MedSloppyPhrase       91.55      (4.4%)       93.24      (2.9%)    1.8% (  -5% -    9%) 0.120
         LowSloppyPhrase      937.13      (5.2%)      954.60      (4.6%)    1.9% (  -7% -   12%) 0.228
              AndHighLow     1449.94      (6.9%)     1487.01      (5.9%)    2.6% (  -9% -   16%) 0.207
                Wildcard      371.16      (5.0%)      380.85      (5.8%)    2.6% (  -7% -   14%) 0.126
                  Fuzzy1      125.51     (11.4%)      129.07     (11.7%)    2.8% ( -18% -   29%) 0.439
    BrowseDateTaxoFacets       31.30      (5.9%)       32.24      (5.8%)    3.0% (  -8% -   15%) 0.105
              AndHighMed      753.84      (7.0%)      776.78      (5.2%)    3.0% (  -8% -   16%) 0.118
              OrHighHigh      116.61      (5.5%)      120.18      (4.0%)    3.1% (  -6% -   13%) 0.042
BrowseDayOfYearTaxoFacets       31.31      (6.2%)       32.33      (6.0%)    3.2% (  -8% -   16%) 0.093
   BrowseMonthTaxoFacets       34.52      (6.0%)       35.65      (5.9%)    3.3% (  -8% -   16%) 0.083
       HighTermMonthSort      986.26     (13.0%)     1021.32     (12.3%)    3.6% ( -19% -   33%) 0.374
                 LowTerm     2537.18      (6.0%)     2629.81      (6.5%)    3.7% (  -8% -   17%) 0.064
                  Fuzzy2       71.19     (20.2%)       75.05     (18.2%)    5.4% ( -27% -   54%) 0.372
   HighTermDayOfYearSort      333.18     (12.6%)      351.31     (13.9%)    5.4% ( -18% -   36%) 0.194
```

**Comment by gf2121** [comment]
> @dweiss Thank you very much for the guiding of how to do a benchmark on Lucene, the lueneutil tool is really nice!
> I repeatedly execute the wikimedium1m 20 times, the following is the result of the last iter. I guess it indicates that the reading performance is stable overall :)
> 
> ```
>                  TaskQPS    baseline   StdDevQPS   my_mod_ver     StdDev          Pct diff     p-value
>        HighTermMonthSort      405.40     (11.6%)      390.20     (11.1%)   -3.7% ( -23% -   21%) 0.295
>                 PKLookup      131.35      (4.5%)      128.26      (6.5%)   -2.4% ( -12% -    9%) 0.183
>                  Respell       88.96      (8.0%)       86.91      (8.7%)   -2.3% ( -17% -   15%) 0.383
>               AndHighLow      611.88      (5.6%)      603.60      (9.2%)   -1.4% ( -15% -   14%) 0.575
> BrowseDayOfYearTaxoFacets       21.70      (7.7%)       21.43      (9.1%)   -1.3% ( -16% -   16%) 0.630
>         HighSloppyPhrase       74.97      (4.8%)       74.10      (8.6%)   -1.2% ( -13% -   12%) 0.601
>    BrowseMonthSSDVFacets       91.65      (4.8%)       90.66      (5.8%)   -1.1% ( -11% -    9%) 0.519
>                MedPhrase      110.37      (8.8%)      109.19      (7.3%)   -1.1% ( -15% -   16%) 0.674
>                OrHighMed      167.04      (8.9%)      165.47      (7.6%)   -0.9% ( -16% -   17%) 0.718
>               OrHighHigh       86.33      (9.1%)       85.61      (7.9%)   -0.8% ( -16% -   17%) 0.755
>              LowSpanNear      156.83      (7.1%)      155.74      (6.5%)   -0.7% ( -13% -   13%) 0.746
>                 Wildcard      139.21      (7.0%)      138.29      (9.8%)   -0.7% ( -16% -   17%) 0.805
> BrowseDayOfYearSSDVFacets       78.95      (5.0%)       78.52      (5.8%)   -0.5% ( -10% -   10%) 0.753
>                   Fuzzy1       76.09      (9.7%)       75.84      (7.7%)   -0.3% ( -16% -   18%) 0.905
>          MedSloppyPhrase       48.37      (5.9%)       48.22      (5.1%)   -0.3% ( -10% -   11%) 0.859
>                   IntNRQ      310.73     (10.5%)      310.11     (12.2%)   -0.2% ( -20% -   25%) 0.955
>                 HighTerm      759.07      (7.3%)      757.84     (12.1%)   -0.2% ( -18% -   20%) 0.959
>    BrowseMonthTaxoFacets       24.17      (9.5%)       24.19     (10.0%)    0.1% ( -17% -   21%) 0.984
>     HighIntervalsOrdered      121.98      (5.8%)      122.10      (7.9%)    0.1% ( -12% -   14%) 0.964
>          LowSloppyPhrase      188.90      (7.8%)      189.42      (5.7%)    0.3% ( -12% -   14%) 0.898
>               AndHighMed      418.22      (9.0%)      420.49      (9.7%)    0.5% ( -16% -   21%) 0.855
>                  MedTerm      874.56      (7.6%)      880.02     (10.9%)    0.6% ( -16% -   20%) 0.833
>              MedSpanNear      378.96      (7.2%)      381.70      (9.2%)    0.7% ( -14% -   18%) 0.781
>                   Fuzzy2       25.74      (9.8%)       25.97     (10.9%)    0.9% ( -17% -   23%) 0.777
>              AndHighHigh      126.51      (6.1%)      127.75      (8.5%)    1.0% ( -12% -   16%) 0.676
>               HighPhrase      165.71      (8.2%)      167.64     (11.3%)    1.2% ( -16% -   22%) 0.708
>     BrowseDateTaxoFacets       21.40     (10.4%)       21.69     (10.0%)    1.3% ( -17% -   24%) 0.682
>                  LowTerm     1032.43      (8.0%)     1049.57     (10.1%)    1.7% ( -15% -   21%) 0.566
>                OrHighLow      228.54      (5.0%)      232.36      (8.5%)    1.7% ( -11% -   15%) 0.446
>             HighSpanNear       93.72      (7.4%)       95.46      (7.3%)    1.9% ( -12% -   17%) 0.427
>    HighTermDayOfYearSort      380.08     (12.2%)      387.47      (9.4%)    1.9% ( -17% -   26%) 0.573
>                LowPhrase      137.13      (8.2%)      140.30      (6.2%)    2.3% ( -11% -   18%) 0.314
>                  Prefix3      290.55     (11.0%)      299.98     (12.9%)    3.2% ( -18% -   30%) 0.390
> ```

Though this result looks fine, i'm still a bit worried about the cost of reading array in some cases, for example, in a different java version. So i updated this PR again to make sure that we only read arrays when the index is a variable. In other case, we still read final longs. There are only 14 lines more than the origin code, which i think can be acceptable :)

**Comment by jpountz** [comment]
Thank you @gf2121 !

**Pull request merged**
