### PR TITLE
Backport a few upgrades to branch_8_11

### PR DESCRIPTION
**Pull request by risdenk**
* SOLR-16424: Upgrade Netty to 4.1.82.Final
* SOLR-16421: Upgrade Apache Calcite to 1.32.0 and Avatica to 1.22.0
* SOLR-16332: Upgrade Jetty to 9.4.48.v20220622
* SOLR-16141: Upgrade Apache Tika to 1.28.4

### CODE REVIEW

**Comment by itygh** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by janhoy** [comment]
Most of these should be safe as they are pure bugfix version upgrades. I see one `.java` class touched, which is also safe.

Can you try to highlight which part of this PR is the most "risky"? I suppose it would be the 5 new jars/parsers pulled in by Tika? Or the addition of new Calcite deps we have not had before?

**Comment by risdenk** [comment]
> Can you try to highlight which part of this PR is the most "risky"? I suppose it would be the 5 new jars/parsers pulled in by Tika? Or the addition of new Calcite deps we have not had before?

Yea it would be the dependency upgrades. They could be incompatible with each other or have other subtle bugs. The guava upgrade is potentially risky - but will see when I run through all the tests shortly. 

I don't think any of these are terrible from a risk perspective.

**Comment by risdenk** [comment]
Well I'm struggling to run tests on my M1 Mac. They don't like JDK 8 on M1. I'll have to test this separately on another computer or VM.

**Comment by janhoy** [comment]
Should there have been an optional GitHub Action to run all tests in a PR? Something you could activate on demand?

**Comment by risdenk** [comment]
> Should there have been an optional GitHub Action to run all tests in a PR? Something you could activate on demand?

eh its only an issue with 8.11 and I have ways to do it just forgot about jdk 8 and M1 being an issue :D I ran into this when testing 8.11.2 release and @madrob helped explain what was going on w/ M1. 

it would be cool but its not something I would spend a ton of time on.

**Review by janhoy — APPROVED** [review]
I'm on M1 too so I'm not going to run all tests. If all tests pass I'm +1.

**Comment by risdenk** [comment]
Took a few runs but got a pass:

```
BUILD SUCCESSFUL
Total time: 75 minutes 41 seconds
```

all the failures didn't reproduce when run independently so I don't think they had anything to do with these fixes.

**Comment by HoustonPutman** [comment]
Sorry tried to get the tests to pass and test this, but it never worked for me 😕

**Pull request merged**
