### PR TITLE
WIP: SOLR-12955: rebase and split changes to smaller commits

### PR DESCRIPTION
**Pull request by barrotsteindev**

### CODE REVIEW

**Comment by dsmiley** [comment]
good start

**Comment by dsmiley** [comment]
I'm not sure if the "base" functionality needed to be in a new class... I could imagine simply adding subclasses and leave DUP named as it is with it's base functionality.  WDYT?  It may help keep git history better too.
p.s. I'm GMT+1 this week

**Comment by barrotsteindev** [comment]
I've continued hacking on this issue last night, and have been facing some issues concerning the base class.
I agree, I'll stash the changes and try tackling this again.
I also found a few places to improve upon the previous PR :)

**Comment by barrotsteindev** [comment]
created a [new PR](https://github.com/apache/lucene-solr/pull/528)

**Pull request closed without merging**
