### PR TITLE
SOLR-7557: Fix parsing of child documents using queryAndStreamResponse

### PR DESCRIPTION
**Pull request by computerlove**

### CODE REVIEW

**Comment by janhoy** [comment]
Great. What's the reason for adding another child document to the test? 

Please do the following changes
* Move the test to `SolrExampleStreamingBinaryTest` (don't need to test it for all clients
* Rename the test `testQueryAndStreamResponse` as it is the response parsing we're testing
* Add this line in `solr/CHANGES.txt` under 7.6.0 version and section "Bug Fixes" (appx line 215)

      * SOLR-7557: Fix parsing of child documents using queryAndStreamResponse (Marvin Bredal Lillehaug via janhoy) 
* Make sure the PR is up-to-date with current master

Then I'll be able to merge it directly and you also get credit in git log :)

**Comment by computerlove** [comment]
I had some rebase/merge problems, getting a very large diff. Tried several times to fix it and keep the commit history for this issue, but ended up having to just apply the patch to a clean master.

**Comment by janhoy** [comment]
Probably the easiest :) Thanks

**Comment by janhoy** [comment]
Hmm, your new commit lacks the changes to the `StreamingBinaryResponseParser` file.

**Comment by computerlove** [comment]
Damn. Now it's there!

**Comment by janhoy** [comment]
Committed. You may close this PR (forgot to add the magic words in the commit msg)

**Pull request closed without merging**
