### PR TITLE
SOLR-15355 - Upgrade hadoop to version 3.2.2 to fix CVE

### PR DESCRIPTION
**Pull request by antogruz**
To do that, I’ve needed to update 2 other files:

1) The HttpServer2.java. It has been forked from hadoop and would not be compatible anymore with this new version. I’ve only patched what was necessary to make the code compile and the test pass

2) TestSolrCloudWithSecureImpersonation.java. This test is checking the exception thrown for some keyword. However, with the new version of hadoop, a different exception is thrown, "invalid IPv6 address". As it seems that the important check in this test is that an exception is raised, I thought that removing this rigid assertion would keep the spirit of the test.

### CODE REVIEW

**Comment by antogruz** [comment]
Hello @markrmiller, I mention you since you added the HttpServer2.java file back in 2016 forking it from hadoop project. Please tell me if we should handle this file another way than patching it when needed. Maybe now that hadoop 3 is here we could directly import it instead of forking it?

**Comment by antogruz** [comment]
Hey @dsmiley, for your information this is the Pull Request about fixing hadoop CVE.

**Comment by markrmiller** [comment]
Forget in test code, so only done to modify something to make the test world happy. Perhaps allowing a file out location customization or something of the like. Don't even know what might be still necessary there after subsequent updates, so anything that has the tests happy is likely fine.

**Comment by dsmiley** [comment]
RE HttpServer2, If tests pass; works for me.
I looked a bit at the assertion you removed about the exception message and it's fine I suppose.  I doubt it's pertinent what the message string actually is.
I'll run tests tonight.  If pass, I'll aim to merge this Friday.

**Review by risdenk — APPROVED** [review]

**Comment by risdenk** [comment]
> The HttpServer2.java. It has been forked from hadoop and would not be compatible anymore with this new version. I’ve only patched what was necessary to make the code compile and the test pass

Ideally we wouldn't need these forks of the Hadoop. I don't remember exactly what changes where in there when I helped merge the updates. There are some security manager fixes in a few of the forked classes as well.

**Pull request merged**
