### PR TITLE
LUCENE-9768: Add source sets for src/tools, clean up forbidden API and formatting errors

### PR DESCRIPTION
**Pull request by dweiss**

### CODE REVIEW

**Comment by dweiss** [comment]
@rmuir Can you check if this works with Eclipse? Tools should be included in classpath now.

**Comment by dweiss** [comment]
Never mind, I see it in the generated .classpath. Should be fine.

**Review by rmuir — COMMENTED** [review]
Thanks for bringing these tools up to the last decade here! it is good to avoid the old java.io stuff, I like good error messages.

**Comment by dweiss** [comment]
I didn't really do much - I just corrected what the forbiddenapis were complaining about. I'm sure you could make them nicer. It's good they're part of the build now though!

**Pull request merged**
