### PR TITLE
SOLR-13985: Bind to localhost interface by default

### PR DESCRIPTION
**Pull request by gerlowskija**
Prior to this commit, Solr's Jetty listened for connections on all
network interfaces. This commit changes it to only listen on localhost,
to prevent incautious administrators from accidentally exposing their
Solr deployment to the world.

Administrators who wish to override this behavior can set the
SOLR_JETTY_HOST property in their Solr include file
(solr.in.sh/solr.in.cmd) to "0.0.0.0" or some other value.

A version of this commit was previously reverted due to inconsistency
between SOLR_HOST and SOLR_JETTY_HOST.  This commit fixes this issue.

# Description
Reinstates the bind-to-localhost functionality, which was previously reverted.  Contains a fix to keep the SOLR_HOST and SOLR_JETTY_HOST properties better aligned by default.

# Tests

The way that our automated tests run, they don't exercise any of this functionality.  So the testing for this was mostly manual.  A lot of my testing was of the form: Start Solr(s) a particular way with particular settings, create a simple collection and a complex collection, index to them both, query them both, try a few other collection-admin actions, and shut everything down.  I did this with a single node deploy, a multi-node deploy, the "cloud" example, a multi-node deploy with SOLR_HOST set (this took some /etc/hosts fiddling), and a multi-node deploy with some localhost-bound nodes and some public ones. 

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `master` branch.
- [x] I have run `ant precommit` and the appropriate test suite.
- [ ] I have added tests for my changes.
- [x] I have added documentation for the [Ref Guide](https://github.com/apache/lucene-solr/tree/master/solr/solr-ref-guide) (for Solr changes only).

### CODE REVIEW

**Comment by gerlowskija** [comment]
This still needs Windows support before it can be merged.  I'm working on that now.

**Comment by gerlowskija** [comment]
`solr.cmd` has the wrong line endings again.  It looks like SOLR-13977 was fixed and then regressed almost immediately with some other changes to the code there.

I attempted to fix this in this PR but the diff in github was confusing and it was hard to be confident that I wasn't discarding other changes to solr.cmd.  So my revised plan is to commit this as-is, and push up a separate PR to change the line endings (and possibly add `.gitattributes` protection for these files).

**Comment by janhoy** [comment]
See https://issues.apache.org/jira/browse/SOLR-13977?focusedCommentId=16984686&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16984686 for my attempt on a .gitattributes file

We could look into a .editorconfig file as well to dictate tab sice, space instead of tabs etc.

**Comment by dsmiley** [comment]
FWIW I find the name chosen here to be confusing.... at a glance, it's not evident this is a *bind* host, as opposed to, say, the host name.  And why is it prefixed by SOLR_ when `jetty.port` isn't?  Or perhaps the `jetty.port` is the odd duck.  Shrug; dunno what to make of the mess.  We have too many similar solr/jetty/host vars (env and sys prop) as I look through the code; hard to know what's what.

**Comment by itygh** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Pull request merged**
