### PR TITLE
ant compile error

### PR DESCRIPTION
**Pull request by cqvip-jq**
error info:
```
[ivy:retrieve]
[ivy:retrieve] :: problems summary ::
[ivy:retrieve] :::: WARNINGS
[ivy:retrieve]          ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve]          ::          UNRESOLVED DEPENDENCIES         ::
[ivy:retrieve]          ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve]          :: org.restlet.jee#org.restlet;2.3.0: configuration not found in org.restlet.jee#org.restlet;2.3.0: 'master'. It was required from org.apache.solr#core;working@BK_4B88D29C compile
[ivy:retrieve]          :: org.restlet.jee#org.restlet.ext.servlet;2.3.0: configuration not found in org.restlet.jee#org.restlet.ext.servlet;2.3.0: 'master'. It was required from org.apache.solr#core;working@BK_4B88D29C compile
[ivy:retrieve]          ::::::::::::::::::::::::::::::::::::::::::::::
```

### CODE REVIEW

**Comment by diegoceccarelli** [comment]
@cqvip-jq  this looks like a problem on your side. Try to remove the `ivy2` cache by removing the `.ivy2/cache` folder in your home and then run `ant ivy-bootstrap` and `ant dist` from the lucene-solr folder..

**Comment by diegoceccarelli** [comment]
`maven.restlet.org` gets redirected to `maven.restlet.com`, LGTM

**Comment by cqvip-jq** [comment]
> `maven.restlet.org` gets redirected to `maven.restlet.com`, LGTM

Maybe  it's my problem only, I use proxy in my network because of GFW.

**Comment by diegoceccarelli** [comment]
Sorry @cqvip-jq my comment was misleading, I think you are right and your patch should be merged..

**Pull request closed without merging**
