### PR TITLE
SOLR-11897 Add web app logging interface auto-refresh toggle. 

### PR DESCRIPTION
**Pull request by tommymh**
Our team wanted to be able to pause the logs, to have a bit more time to go over stack traces.

### CODE REVIEW

**Comment by BramVer** [comment]
This would be a very welcome addition to the page, strange that it isn't there in the first place.
Don't know how people deal with logging because right now it is not possible for me to read anything if they all close after 10 seconds :)

**Comment by tflobbe** [comment]
@tommymh Would you mind creating a [Jira issue](https://issues.apache.org/jira/projects/SOLR) for visibility. You can also rename this PR to include the Jira code, that way they'll be linked

**Comment by tommymh** [comment]
Is this desired functionality?  I'm happy to work on it to make any requested changes.

**Comment by ctargett** [comment]
I took a look at this and built it to see how it worked, and it looks good. The diff here, though, has issues applying cleanly after other changes since this was submitted. I was able to figure out how to get it to apply though with some small edits but since our github-jira workflow is so broken it seems easier to me to provide the updated patch on the issue, which I'll do momentarily before committing.

**Pull request closed without merging**
