### PR TITLE
LUCENE-9737: Flexible configuration for DocValue compressions

### PR DESCRIPTION
**Pull request by jaisonbi**
# Description

LUCENE-9211 added compression for Binary DocValues.
LUCENE-9663 added compression for Terms Dict from SortedSet/Sorted DocValues.
LUCENE-9378 made Binary DocValues compression configurable, it introduced two modes for DocValues(Similar with the two modes from Lucene87StoredFieldsFormat): 
- BEST_SPEED
- BEST_COMPRESSION

It's simple to use...so Terms-dict compression shares the same configuration before this PR.But some users may only want to try Terms Dict compression, since Binary DocValue compression may cause performance reduction..

So we need to make configuration flexible. 

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `master` branch.
- [x] I have run `./gradlew check`.
- [x] I have added tests for my changes.
- [ ] I have added documentation for the [Ref Guide](https://github.com/apache/lucene-solr/tree/master/solr/solr-ref-guide) (for Solr changes only).

### CODE REVIEW

**Comment by rmuir** [comment]
Why do we need this? I don't understand why the terms dict compression needs to be configurable at all.

**Comment by jpountz** [comment]
+1 to not have an option to turn off compression of doc values terms dicts

**Comment by jaisonbi** [comment]
> Why do we need this? I don't understand why the terms dict compression needs to be configurable at all.

Under BEST_COMPRESSION mode:
1.  fdt file will be compressed by DEFLATE.
2. terms dict compression and binary DocValue compression will be enabled together.

But some users may just want to try terms dict compression, without enabling binary DocValue compression and DEFLATE...so this PR makes the configuration more flexible...

**Comment by jaisonbi** [comment]
@jpountz @rmuir @bruno-roustant
should I continue this PR?  Please share your comment, thanks.

**Comment by bruno-roustant** [comment]
@jaisonbi this PR has already been commented. The preferred way to configure compression beyond the speed/compression Mode is to use PerField customization.

**Comment by jaisonbi** [comment]
ok...I close this PR first..thanks:)

**Pull request closed without merging**
