### PR TITLE
TieredMergePolicy.findMerges improvements

### PR DESCRIPTION
**Pull request by outcoldman**
Calculate the total size of index from the beginning by excluding too
big segments.
When finding all the merges take in account that merges also produces
segments.

Just something I have found while looking on the code and understanding how default elasticsearch settings applies to lucese merging strategy. 
Not sure if that worth the effort of taking in master. 
I have not tested it and have not even tried to compile.

### CODE REVIEW

**Comment by outcoldman** [comment]
Also looking a little bit more on the code. As I understand segments with size larger than `maxMergedSegmentBytes/2.0` never will be included in any merges, even if amount of deleted documents will be more than `forceMergeDeletesPctAllowed`. And the only option to reclaim the space is to force the merges. (using force merge api from Elasticsearch).
Is that expected or a bug?

**Comment by outcoldman** [comment]
Also, I am right that if you will end up with segment of size (maxMergedSegmentBytes/2.0 - 1) so it is basically a high chance, that this segment will never be merged, because there are will be no segments with size of `1 byte`. Considering that this segment does not have any deletes.

**Comment by atris** [comment]
Is this still relevant?

**Comment by atris** [comment]
Closing as stale

**Pull request closed without merging**
