### PR TITLE
LUCENE-8942: Tighten Up LRUQueryCache's Methods

### PR DESCRIPTION
**Pull request by atris**

### CODE REVIEW

**Comment by atris** [comment]
Gentle ping. Any chance we could commit this?

**Comment by atris** [comment]
Could we merge this? Seems safe enough to merge?

**Comment by jpountz** [comment]
Sorry for the lag, I was off for the last 5 weeks. I'll merge the change soon. I see the CHANGES entry is in 9.0 for now, maybe we should get it in 8.x too to keep backports clean?

**Comment by atris** [comment]
> Sorry for the lag, I was off for the last 5 weeks.

No sweat, welcome back!

> I see the CHANGES entry is in 9.0 for now, maybe we should get it in 8.x too to keep backports clean?

Sure, I will add a CHANGES entry for 8.x (whichever x is the latest)

**Comment by jpountz** [comment]
To avoid any confusion, I was expecting you would move the CHANGES entry on this PR rather than after the merge.

**Comment by atris** [comment]
Yeah, I will move it in this PR itself -- sorry, this one fell off my radar.

**Comment by atris** [comment]
@jpountz Updated, please let me know if it looks fine

**Comment by jpountz** [comment]
This looks great.

**Comment by atris** [comment]
Thank you for merging!

**Pull request merged**
