### PR TITLE
SOLR-13806: change type of QueryResponse._explainMap

### PR DESCRIPTION
**Pull request by gunasekhardora**
# Description

QueryResponse._explainMap is of the type Map<String, String>. When debug.explain.structured=true is used, it throws 
```
java.lang.ClassCastException: class org.apache.solr.common.util.SimpleOrderedMap cannot be cast to class java.lang.String
```

# Solution

Changed the type of this field to Map<String, Object>.

# Tests

Verified if this field is correctly typed for a sample response in the given scenario.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I am authorized to contribute this code to the ASF and have removed any code I do not have a license to distribute.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `master` branch.
- [x] I have run `ant precommit` and the appropriate test suite.
- [x] I have added tests for my changes.
- [ ] I have added documentation for the [Ref Guide](https://github.com/apache/lucene-solr/tree/master/solr/solr-ref-guide) (for Solr changes only).

### CODE REVIEW

**Comment by sigram** [comment]
Hi - this change looks correct but it also needs a unit test, to make sure the original problem explained in the Jira issue is fixed.

**Comment by gunasekhardora** [comment]
@sigram Added an unit test for the same. Please verify it.

**Comment by sigram** [comment]
@gunasekhardora this has been merged manually, can you please close this PR? Thanks!

**Comment by gunasekhardora** [comment]
Closing it @sigram

**Pull request closed without merging**
