### PR TITLE
SOLR-14777: Fix an ignore test that is helpful.

### PR DESCRIPTION
**Pull request by MarcusSorealheis**
# Description

There are a number of tests that are annotated `@Ignore` but we still need them. This is a first step to start to chip away at the ignores so that the team is no impacted.

# Solution

 Fix an ignore test that is helpful.

# Tests

I am adding a test that was previously ignored.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `master` branch.
- [x] I have run `ant precommit` and the appropriate test suite.
- [x] I have added tests for my changes.
- [x] I have added documentation for the [Ref Guide](https://github.com/apache/lucene-solr/tree/master/solr/solr-ref-guide) (for Solr changes only).

### CODE REVIEW

**Comment by MarcusSorealheis** [comment]
@markrmiller Is this the right idea for removing ignores?

**Comment by MarcusSorealheis** [comment]
image

**Comment by MarcusSorealheis** [comment]
I am seeing issues on pre-commit but I did not change any of those files. They should be fine: 
```
BUILD FAILED
/home/runner/work/lucene-solr/lucene-solr/build.xml:128: Found 489 violations in source files (invalid logger name [log, uses static class name, not specialized logger], invalid logging pattern [not private static final, uses static class name], nocommit).
```

**Comment by MarcusSorealheis** [comment]
I'm inclined to believe that there is another test that is no longer so flakey that also extends `EmbeddedSolrServerTestBase` but I want to keep the scope limited for reviews because of _other_ challenging tests in the branch atm.

**Comment by thelabdude** [comment]
Precommit won't work on this branch as there are many `nocommit` in the code (obviously).

**Comment by thelabdude** [comment]
@MarcusSorealheis thanks for helping out with this branch. The `SolrPingTest` passes for me locally w/o your fixes, which is not surprising for ignored tests as a previous issue may have been resolved by other changes in this very active branch. However, I'm not clear on the reasons for your changes in the `SolrZkServer` class? For instance, `server.addr` is a `InetSocketAddress` so doing an `equals` on that to a String is not what we want here:
```
-      if (server.addr.getHostName().equals(myHost)) {
+      if (server.addr.equals(myHost)) {
```

**Comment by MarcusSorealheis** [comment]
@thelabdude That's right. We need to compare the hostname. If the test is no longer broken, then this is fine to close.

**Comment by markrmiller** [comment]
> @markrmiller Is this the right idea for removing ignores?

This is the right idea though, as Tim says, some of these tests may already be okay due to other changes.

But basically, remove the ignores, if they don't pass address the issues, if the test is much slower than 10 seconds total (not just what junit reports) move it to @Nightly.

**Pull request closed without merging**
