### PR TITLE
LUCENE-9427: Ensure unified highlighter considers all terms in fuzzy query.

### PR DESCRIPTION
**Pull request by jtibshirani**
This fixes a regression where if a fuzzy query corresponds to an exact match
(for example it has maxEdits: 0), then the unified highlighter doesn't produce
highlights for the matching terms.

The proposed fix is to always pass back an automaton when visiting a fuzzy
query. This seems to match the previous behavior before the regression was
introduced.

### CODE REVIEW

**Comment by jtibshirani** [comment]
It looks like this behavior changed during the `QueryVisitor` refactor: https://github.com/apache/lucene-solr/pull/581/files#diff-449ea2758bc22783ca3f819096e1b638R97. Previously we always extracted an automaton from fuzzy queries.

**Comment by romseygeek** [comment]
Related: https://issues.apache.org/jira/browse/LUCENE-9274

I think ideally the fix would be https://issues.apache.org/jira/browse/LUCENE-9277, but this works as a stopgap.

**Comment by jtibshirani** [comment]
Thanks @romseygeek for taking a look. What do you see as the next steps? Would it make sense to merge this, and I could look into LUCENE-9277 in a follow-up?

**Comment by jtibshirani** [comment]
I just pushed a changelog update.

**Comment by romseygeek** [comment]
Merged to master in 688583fc2d01c39bba63d19cf57bb5720eda1afd

**Pull request closed without merging**
