### PR TITLE
Use The Passed In Threshold Value in doConcurrentSearchWithThreshold

### PR DESCRIPTION
**Pull request by atris**

### CODE REVIEW

**Comment by atris** [comment]
Can we merge this one? This is a simple fix to an existing test method.

**Comment by msokolov** [comment]
I'll commit it. As I looked at this I couldn't help noticing a little spelling nit; we have {{thresHold}} but "threshold" is a single word, so it'd look nicer without the camel case I think :)

**Comment by atris** [comment]
Thanks, missed the camel casing, fixed now

**Comment by msokolov** [comment]
thanks! merged

**Comment by atris** [comment]
Thanks!

**Pull request merged**
